
LADEVORGANG...					// LOADING...

START DRÜCKEN					//	PRESS START

MEMORY CARD WIRD ÜBERPRÜFT		// CHECKING MEMORY CARD

DU KANNST NUR SPIELE			// YOU WILL NOT BE ABLE TO SAVE
SPEICHERN, WENN DU EINE			// ANY GAMES UNLESS YOU INSERT A
MEMORY CARD IN DEN				// MEMORY CARD IN THE
MEMORY CARD STECKPLATZ EINLEGST	// MEMORY CARD SLOT INSERTED

WEITER							// CONTINUE

ERNEUT VERSUCHEN				// TRY AGAIN

MEMORY CARD IST					// MEMORY CARD IS
NICHT EINGELEGT IN				// NOT INSERTED IN
MEMORY CARD						// MEMORY CARD
STECKPLATZ...					// SLOT

ZU ÜBERSCHREIBENDES				// TO OVERWRITE
SPIEL AUSWÄHLEN					// GAME SELECT

ZU ÜBERSCHREIBENDE				// TO OVERWRITE
WIEDERHOLUNG AUSWÄHLEN			// REPLAY SELECT

NICHT GENÜGEND					// NOT ENOUGH
FREIE SPEICHERBLÖCKE			// FREE BLOCKS
AUF DER MEMORY CARD				// ON THE MEMORY CARD
VERFÜGBAR						// AVAILABLE

FEHLER BEIM						// ERROR WHEN
VERWENDEN DER					// USING THE
MEMORY CARD						// MEMORY CARD

DATENFEHLER IN					// DATA ERROR IN
GESPEICHERTER					// SAVED
WIEDERHOLUNGSDATEI				// REPLAY FILE

SPIELDATEI						// GAME FILE

KEINE GESPEICHERTEN				// NO SAVED
WIEDERHOLUNGSDATEIEN			// REPLAY FILES
AUF DER MEMORY CARD				// ON THE MEMORY CARD

KEINE GESPEICHERTEN				// NO SAVED
SPIELDATEIEN					// GAME FILES
AUF DER MEMORY CARD				// ON THE MEMORY CARD

SPIEL WIRD VON					// GAME ON THE
MEMORY CARD GELADEN				// MEMORY CARD LOADING

WIEDERHOLUNG WIRD VON			// REPLAY ON THE
MEMORY CARD GELADEN				// MEMORY CARD LOADING

SPIEL WIRD VON					// GAME ON THE
MEMORY CARD GELÖSCHT			// MEMORY CARD DELETING

WIEDERHOLUNG WIRD				// REPLAY ON THE
VON MEMORY CARD					// THE MEMORY CARD
GELÖSCHT						// DELETING

FORMATIERUNG DER				// FORMAT THE
MEMORY CARD						// MEMORY CARD
ABGESCHLOSSEN					// COMPLETED

FORMATIERUNG DER				// FORMAT THE
MEMORY CARD						// MEMORY CARD
GESCHEITERT						// FAILED

MEMORY CARD IST					// MEMORY CARD IS
NICHT FORMATIERT,				// NOT FORMATTED
JETZT FORMATIEREN?				// PERFORM FORMAT?

MEMORY CARD						// MEMORY CARD
WIRD FORMATIERT,				// FORMATTING
BITTE WARTEN...					// PLEASE WAIT

MAXIMALE ZAHL AN				// MAXIMUM NUMBER OF
SPIELDATEIEN WURDE				// GAME FILES ARE
GESPEICHERT						// SAVED

MAXIMALE ZAHL AN				// MAXIMUM NUMBER OF
WIEDERHOLUNGSDATEIEN			// REPLAY FILES
WURDE GESPEICHERT				// ARE SAVED

WIEDERHOLUNG WIRD				// REPLAY ON THE
AUF MEMORY CARD					// MEMORY CARD
GESPEICHERT,					// SAVING
BITTE WARTEN...					// PLEASE WAIT

SPIEL WIRD						// GAME ON
AUF MEMORY CARD					// THE MEMORY CARD
GESPEICHERT,					// SAVING
BITTE WARTEN...					// PLEASE WAIT

SPEICHERN ABBRECHEN				// CANCEL SAVE

ABBRECHEN						// CANCEL

DIE MEMORY CARD					// THE MEMORY CARD
WIRD ÜBERPRÜFT,					// NOW CHECKING
BITTE WARTEN...					// PLEASE WAIT

DAS SPIEL						// THE GAME
WURDE AUF DIE					// IS ON THE 
MEMORY CARD						// MEMORY CARD
GESPEICHERT						// SAVED

DIE WIEDERHOLUNG				// THE REPLAY
WURDE AUF DIE					// IS ON THE 
MEMORY CARD						// MEMORY CARD
GESPEICHERT						// SAVED

WASSERSPORTARTEN				// WATER SPORTS

KALIFORNISCHER WASSERSPORT		// CALIFORNIA WATER SPORTS

SPIELSTATUS						// GAME STATE

SPIEL STARTEN					// START GAME

MIT BELIEBIGER TASTE BEENDEN	// PRESS ANY BUTTON TO QUIT

WIEDERHOLUNG NUMMER 1			// REPLAY NUMBER 1

SPIEL NUMMER 1					// GAME NUMBER 1

SPIEL LADEN						// GAME LOAD

MEISTERSCHAFT LADEN				// CHAMPIONSHIP LOAD

WIEDERHOLUNG LADEN				// REPLAY LOAD

ZU LADENDES						// TO LOAD
SPIEL AUSWÄHLEN					// GAME SELECT

ZU LADENDE						// TO LOAD
WIEDERHOLUNG AUSWÄHLEN			// REPLAY SELECT

ZU ÜBERSCHREIBENDES				// TO OVERWRITE
SPIEL AUSWÄHLEN					// GAME SELECT

ZU ÜBERSCHREIBENDE				// TO OVERWRITE
WIEDERHOLUNG AUSWÄHLEN			// REPLAY SELECT

OPTIONEN						// OPTIONS

BEENDEN							// QUIT

WIEDER AUFNEHMEN				// RESUME

BEWERTUNG						// JUDGING

SOFORTIGE WIEDERHOLUNG			// INSTANT REPLAY

WIEDERHOLUNG SPEICHERN			// REPLAY SAVE

ALS NEU SPEICHERN				// AS NEW SAVE

ÜBERSCHREIBEN					// OVERWRITE

ZEITLUPENSPRUNG (SLOW MOTION AIR)	// SLOMO AIR

BILDSCHIRM EINSTELLEN			// ADJUST SCREEN

SOUND							// SOUND

MUSIK							// MUSIC

AUSWÄHLEN						// SELECT

ZURÜCK							// GO BACK

KEIN CONTROLLER,				// NO CONTROLLER
BITTE ANSCHLIESSEN				// PLEASE ATTACH

KEINE UNTERSTÜTZEN CONTROLLER	// NO SUPPORTED CONTROLLER
ENTDECKT, BITTE CONTROLLER		// DETECTED, PLEASE CONTROLLER	
ANSCHLIESSEN					// ATTACH

BITTE CONTROLLER IN				// PLEASE CONTROLLER IN
CONTROLLER ANSCHLUSS 1			// CONTROLLER SLOT 1
ANSCHLIESSEN					// ATTACH

WEITER MIT START				// PRESS START TO CONTINUE

ANSCHLUSS 1						// PORT 1

TRAININGSMODUS					// FREERIDE

GETEILTER BILDSCHIRM			// SPLIT SCREEN

BIG AIR							// BIG AIR

STRANDWETTBEWERB				// BEACH CONTEST

SPORTLERMEISTERSCHAFT			// RIDER CHAMPIONSHIP

EXTREMTRICK						// EXTREME TRICK

BIG AIR-WETTBEWERB				// BIG AIR COMPETITION

WELLENREITERWETTBEWERB			// WAVE RIDING COMPETITION

WELLENREITERMEISTERSCHAFT		// WAVE RIDING CHAMPIONSHIP

EXTREMTRICKWETTBEWERB			// EXTREME TRICK COMPETITION

SPORT AUSWÄHLEN					// SPORT SELECT

SURFEN							// SURFING

WASSERJET						// JET WATERCRAFT

WINDSURFEN						// WINDSURFING

BODYBOARDING					// BODYBOARDING

BILDSCHIRM ZENTRIEREN			// CENTRE SCREEN

STEUERUNG						// CONTROLS

VIBRATION: EIN					// VIBRATION: ON

ZAHL DER						// NUMBER OF
SPIELER?						// PLAYERS?

MAX. WARTEZEIT					// MAX TIME	
AUF WELLE?						// FOR WAVE?

SITZUNGSDAUER?					// SESSION TIME?

WELLENREITZEIT					// WAVE TIME

WELLENREITER AUSWÄHLEN			// SESSION TIME SELECT

MARK
SUMMER
CRYSTAL
CAM
BEAR
TANIA
CHOOK
JAIMIE

BOOT AUSWÄHLEN					// CRAFT SELECT

STRAND AUSWÄHLEN				// BEACH SELECT

LAGUNA BEACH

SAN DIEGO

TORREY PINE

BIG SUR COAST

SANTA CRUZ

SONOMA COAST

FORT BRAGG

MALIBU

BOARD AUSWÄHLEN					// BOARD SELECT

S1 (SPIELER 1)					// P1 (PLAYER 1)

MENÜ TESTMODUS					// MENU TESTMODE

SPIELER							// PLAYER
BEREIT?							// READY?

DRÜCKEN (TASTE DRÜCKEN)			// PRESS (button)

SICHER?							// ARE YOU SURE?

SPIELSTATUS SPEICHERN?			// SAVE GAME STATE?

SPIELSTATUS SPEICHERN

JA								// YES

NEIN							// NO	

EIN								// ON

AUS								// OFF	

BIG AIR-ERGEBNISSE				// BIG AIR RESULTS

NAME							//

GRÖSSE							// HEIGHT

ORT								// PLACE

BIG AIR-GEWINNER				// BIG AIR WINNER

GLÜCKWUNSCH, MARK				// CONGRATULATIONS MARK

NOCH EINMAL SPIELEN?			// PLAY AGAIN?

PUNKTBEWERTUNG					// SCORE

ERGEBNISSE DES STRANDWETTBEWERBS	// BEACH CONTEST RESULTS

SPORTLERMEISTERSCHAFTSERGEBNISSE	// RIDER CHAMPIONSHIP RESULTS

SIEGER DER STRANDMEISTERSCHAFT		// CHAMPIONSHIP BEACH WINNER

SIEGER DES STRANDWETTBEWERBS		// BEACH CONTEST WINNER

GESAMTPUNKTE					// POINTS

MEISTERSCHAFTPLATZIERUNGEN		// CHAMPIONSHIP PLACINGS

MEISTERSCHAFTSSIEGER			// CHAMPIONSHIP WINNER

EXTREMTRICK-ERGEBNISSE			// EXTREME TRICK RESULTS

SIEGER DER EXTREMTRICKS			// EXTREME TRICK WINNER

RICHTERPUNKTZAHL?				// JUDGES SCORE?

WELLENPUNKTZAHL					// WAVE SCORE

NÄCHSTER STRAND					// NEXT BEACH

SPIEL SPEICHERN					// SAVE GAME

PLATZIERUNGEN ZEIGEN			// SHOW PLACINGS

BESTE							// BEST

HÖCHSTE							// HIGHEST

AKTUELLE						// CURRENT

IN DER LUFT						// AIR (IN THE AIR)

PUNKTZAHL 1						// SCORE 1

PUNKTZAHL 2

PUNKTZAHL 3

WETTKAMPF						// CONTEST

MEISTERSCHAFT					// CHAMPIONSHIP

EXTREM							// EXTREME
	
WIEDERHOLUNG					// REPLAY

DEMO							

GRAFIKEN						// GRAPHICS

CUTBACK

FORWARD SPIN

REVERSE SPIN

AIR ROLL

EL ROLLO

BARREL ROLL

INVERTED AIR

AIR FORWARD SPIN

AIR REVERSE SPIN

AIR ROLL SPIN

BACKFLIP

FRONTFLIP

DOUBLE AIR ROLL

DOUBLE EL ROLLO

DOUBLE BARREL ROLL

DOUBLE REVERSE AIR

DOUBLE FORWARD AIR

UNBEKANNT							// UNKNOWN

BIG AIR

REENTRY

AIR REENTRY

THREE SIXTY

BOTTOM HAND TURN

LAUTSTÄRKE							// VOLUME

BARREL RIDE!

FRONT AIR THREE SIXTY

BACK AIR THREE SIXTY

FRONT AIR SEVEN TWENTY

BACK AIR SEVEN TWENTY

SUPERMANN!							// 

AIR ONE EIGHTY

BRONCO AIR ONE EIGHTY

WHITE HOT

LEAP FROG

THE DART

WAVE JUMPER

OCEAN BLUE

WAVE RIDER

TRAININGSMODUS						// FREE RIDE?

BUMP N JUMP

SLASH

YELLOW CURL

PACIFIC BLUE

QUICK SNAP

STYLE RIDER

REDBACK

SHARK TOOTH

SUNSET

PINE LIME

SWISH

POISON TIP

TRAININGSMODUS

TUBES RULE

FLAME OUT

RAINBOW

IN ZONE

CONCEPT

SWIFT

CANNIBAL

DART

DEVIL_RAY

PRO X5T

MIRAGE IV

SABRE PRO

WINGNUT

TYPHOON

CYCLONE

HURRICANE

STRANDKAMERA (KAMERA)			// BEACH CAMERA

BOOTKAMERA						// BOAT CAMERA

LEUCHTTURMKAMERA				// LIGHTHOUSE CAMERA

TUBE-KAMERA						// TUBE CAMERA

BARREL-KAMERA					// BARREL CAMERA	

MÖVENSICHT						// SEAGULL CAMERA

GESPERRT						// LOCKED

ALLE STRANDSPERREN				// ALL BEACHES
MÜSSEN AUFGEHOBEN				// MUST BE
WERDEN, UM						// UNLOCKED, FOR
SPIEL ZU STARTEN				// GAME TO START

DU HAST DIE						// YOU HAVE THE
STRANDSPERRE .......			// BEACH
AUFGEHOBEN						// UNLOCKED	

HÖCHSTER AIRTRICK				// HIGHEST AIR

EXTREMPUNKTZAHL					// EXTREME SCORE

SCHWIERIGKEIT FÜR S1 (SPIELER 1)	// DIFFICULTY FOR P1
AUSWÄHLEN							// SELECT

WELLENREITERKÖNNEN FÜR S1 (SPIELER 1)	// SKILL FOR P1
AUSWÄHLEN								// SELECT

SPINNER (ANFÄNGER)						// KOOK

AMATEUR									// 

PRO (PROFI)								// 

FÜR DIESEN STRAND						// WIN BEACH
MUSS 1 SPIELER-							// 1 PLAYER
STRANDWETTKAMPF							// BEACH CONTEST
GEWONNEN WERDEN							// TO UNLOCK

WAVE BLASTER WB760

WAVE BLASTER WB800

SUPER JET 700

WAVE RUNNER GP800

WAVE RUNNER GP1200R

760CC SIT DOWN

800CC SIT DOWN

700CC STAND UP

800CC SIT DOWN

1200CC SIT DOWN
