/**********************************************************
 * Copyright (C) 1999,2000 TheyerGFX Pty Ltd
 * All Rights Reserved
 **********************************************************
 * Project:	PlayStation surf game
 **********************************************************
 * File:	surftxt.h
 * Author:	Mark Theyer
 * Created:	01 Jun 2000
 **********************************************************
 * Description:	Message text strings for each language
 **********************************************************
 * Revision History:
 * 01-Jun-00	Theyer	Initial coding.
 **********************************************************/

#ifndef THEYER_SURFTXT_H
#define THEYER_SURFTXT_H

/*
 * includes
 */

/*
 * macros
 */

static char *english_text[] = {
	" ",										//   0 SURF_MSG_BLANK
	"LOADING...",								//   1 SURF_MSG_LOADING
	"PRESS START",								//   2 SURF_MSG_PRESS_START
	"CHECKING MEMORY CARD",						//   3 SURF_MSG_CHECKING_MEMORY_CARD
	"YOU WILL NOT BE ABLE TO SAVE",				//   4 SURF_MSG_YOU_WILL_NOT_BE_ABLE_TO_SAVE
	"ANY GAMES UNLESS YOU INSERT A",			//   5 SURF_MSG_ANY_GAMES_UNLESS_YOU_INSERT_A	
	"MEMORY CARD INTO THE",						//   6 SURF_MSG_MEMORY_CARD_INTO_THE			
	"MEMORY CARD SLOT",							//   7 SURF_MSG_MEMORY_CARD_SLOT				
	"CONTINUE",									//   8 SURF_MSG_CONTINUE						
	"TRY AGAIN",								//   9 SURF_MSG_TRY_AGAIN						
	"MEMORY CARD IS",							//  10 SURF_MSG_MEMORY_CARD_IS					
	"NOT INSERTED INTO",						//  11 SURF_MSG_NOT_INSERTED_INTO				
	"THE MEMORY CARD",							//  12 SURF_MSG_THE_MEMORY_CARD				
	"SLOT...",									//  13 SURF_MSG_SLOT							
	"TO OVERWRITE",								//  14 SURF_MSG_TO_OVERWRITE					
	"INSUFFICIENT",								//  15 SURF_MSG_INSUFFICIENT					
	"FREE BLOCKS",								//  16 SURF_MSG_FREE_BLOCKS					
	"AVAILABLE ON",								//  17 SURF_MSG_AVAILABLE_ON					
	"THERE WAS AN",								//  18 SURF_MSG_THERE_WAS_AN					
	"ERROR WHEN",								//  19 SURF_MSG_ERROR_WHEN						
	"USING THE MEMORY",							//  20 SURF_MSG_USING_THE_MEMORY				
	"CARD",										//  21 SURF_MSG_CARD							
	"THERE WAS A",								//  22 SURF_MSG_THERE_WAS_A					
	"DATA ERROR",								//  23 SURF_MSG_DATA_ERROR						
	"IN THE SAVED",								//  24 SURF_MSG_IN_THE_SAVED					
	"REPLAY FILE",								//  25 SURF_MSG_REPLAY_FILE					
	"GAME FILE",								//  26 SURF_MSG_GAME_FILE						
	"THERE ARE NO",								//  27 SURF_MSG_THERE_ARE_NO					
	"SAVED REPLAY",								//  28 SURF_MSG_SAVED_REPLAY					
	"FILES ON THE",								//  29 SURF_MSG_FILES_ON_THE					
	"MEMORY CARD",								//  30 SURF_MSG_MEMORY_CARD					
	"SAVED GAME",								//  31 SURF_MSG_SAVED_GAME						
	"LOADING GAME",								//  32 SURF_MSG_LOADING_GAME					
	"FROM THE MEMORY",							//  33 SURF_MSG_FROM_THE_MEMORY				
	"LOADING REPLAY",							//  34 SURF_MSG_LOADING_REPLAY					
	"DELETING GAME",							//  35 SURF_MSG_DELETING_GAME					
	"DELETING REPLAY",							//  36 SURF_MSG_DELETING_REPLAY				
	"FORMAT",									//  37 SURF_MSG_FORMAT							
	"COMPLETED",								//  38 SURF_MSG_COMPLETED						
	"FAILED",									//  39 SURF_MSG_FAILED							
	"UNFORMATTED",								//  40 SURF_MSG_UNFORMATTED					
	"FORMAT NOW?",								//  41 SURF_MSG_FORMAT_NOW_Q					
	"FORMATTING",								//  42 SURF_MSG_FORMATTING						
	"PLEASE WAIT...",							//  43 SURF_MSG_PLEASE_WAIT					
	"THE MAXIMUM",								//  44 SURF_MSG_THE_MAXIMUM					
	"NUMBER OF",								//  45 SURF_MSG_NUMBER_OF						
	"GAME FILES",								//  46 SURF_MSG_GAME_FILES						
	"REPLAY FILES",								//  47 SURF_MSG_REPLAY_FILES					
	"HAVE BEEN SAVED",							//  48 SURF_MSG_HAVE_BEEN_SAVED				
	"SAVING REPLAY TO",							//  49 SURF_MSG_SAVING_REPLAY_TO				
	"SAVING GAME TO",							//  50 SURF_MSG_SAVING_GAME_TO					
	"CANCEL SAVE",								//  51 SURF_MSG_CANCEL_SAVE					
	"CANCEL",									//  52 SURF_MSG_CANCEL							
	"CHECKING",									//  53 SURF_MSG_CHECKING						
	"THE GAME",									//  54 SURF_MSG_THE_GAME						
	"THE REPLAY",								//  55 SURF_MSG_THE_REPLAY						
	"HAS BEEN SAVED",							//  56 SURF_MSG_HAS_BEEN_SAVED					
	"TO THE MEMORY",							//  57 SURF_MSG_TO_THE_MEMORY					
	"WATERSPORTS",								//  58 SURF_MSG_WATER_SPORTS					
	"GAME STATE",								//  59 SURF_MSG_GAME_STATE						
	"START GAME",								//  60 SURF_MSG_START_GAME						
	"PRESS ANY BUTTON TO QUIT",					//  61 SURF_MSG_PRESS_ANY_BUTTON_TO_QUIT		
	"REPLAY NUMBER",							//  62 SURF_MSG_REPLAY_NUMBER					
	"GAME NUMBER",								//  63 SURF_MSG_GAME_NUMBER					
	"LOAD GAME",								//  64 SURF_MSG_LOAD_GAME						
	"LOAD CHAMPIONSHIP",						//  65 SURF_MSG_LOAD_CHAMPIONSHIP				
	"LOAD REPLAY",								//  66 SURF_MSG_LOAD_REPLAY					
	"SELECT GAME",								//  67 SURF_MSG_SELECT_GAME					
	"SELECT REPLAY",							//  68 SURF_MSG_SELECT_REPLAY					
	"TO LOAD",									//  69 SURF_MSG_TO_LOAD						
	"OPTIONS",									//  70 SURF_MSG_OPTIONS						
	"QUIT",										//  71 SURF_MSG_QUIT							
	"RESUME",									//  72 SURF_MSG_RESUME							
	"JUDGING",									//  73 SURF_MSG_JUDGING						
	"INSTANT REPLAY",							//  74 SURF_MSG_INSTANT_REPLAY					
	"SAVE REPLAY",								//  75 SURF_MSG_SAVE_REPLAY					
	"SAVE AS NEW",								//  76 SURF_MSG_SAVE_AS_NEW					
	"OVERWRITE",								//  77 SURF_MSG_OVERWRITE						
	"SLOMO AIR",								//  78 SURF_MSG_SLOMO_AIR						
	"ADJUST SCREEN",							//  79 SURF_MSG_ADJUST_SCREEN					
	"SOUND",									//  80 SURF_MSG_SOUND							
	"MUSIC",									//  81 SURF_MSG_MUSIC							
	"SELECT",									//  82 SURF_MSG_SELECT							
	"GO BACK",									//  83 SURF_MSG_GO_BACK						
	"CONTROLLER REMOVED",						//  84 SURF_MSG_CONTROLLER_REMOVED
	"THE CONTROLLER",							//  85 SURF_MSG_THE_CONTROLLER			
	"PRO BODYBOARDING",							//  86 SURF_MSG_PRO_BODYBOARDING
	"QUIT GAME?",								//  87 SURF_MSG_QUIT_GAME_Q
	"PLEASE REINSERT",							//  88 SURF_MSG_PLEASE_REINSERT				
	"A CONTROLLER INTO",						//  89 SURF_MSG_A_CONTROLLER_INTO				
	"CONTROLLER PORT 1",						//  90 SURF_MSG_CONTROLLER_PORT_1				
	"PRESS START TO CONTINUE",					//  91 SURF_MSG_PRESS_START_TO_CONTINUE		
	"CONTROLLER PORT",							//  92 SURF_MSG_CONTROLLER_PORT							
	"FREERIDE",									//  93 SURF_MSG_FREERIDE						
	"SPLIT SCREEN",								//  94 SURF_MSG_SPLIT_SCREEN					
	"BIG AIR",									//  95 SURF_MSG_BIG_AIR						
	"BEACH CONTEST",							//  96 SURF_MSG_BEACH_CONTEST					
	"RIDER CHAMPIONSHIP",						//  97 SURF_MSG_RIDER_CHAMPIONSHIP				
	"EXTREME TRICK",							//  98 SURF_MSG_EXTREME_TRICK					
	"SELECT SPORT",								//  99 SURF_MSG_SELECT_SPORT					
	"SURFING",									// 100 SURF_MSG_SURFING						
	"JET WATERCRAFT",							// 101 SURF_MSG_JET_WATERCRAFT					
	"WINDSURFING",								// 102 SURF_MSG_WINDSURFING					
	"BODYBOARD RIDING",							// 103 SURF_MSG_BODYBOARD_RIDING				
	"CENTRE SCREEN",							// 104 SURF_MSG_CENTRE_SCREEN					
	"CONTROLS",									// 105 SURF_MSG_CONTROLS						
	"VIBRATION",								// 106 SURF_MSG_VIBRATION						
	"BIG AIR COMPETITION",						// 107 SURF_MSG_BIG_AIR_COMPETITION				
	"PLAYERS?",									// 108 SURF_MSG_PLAYERS_Q						
	"CATCH A WAVE",								// 109 SURF_MSG_CATCH_A_WAVE					
	"TIME LIMIT?",								// 110 SURF_MSG_TIME_LIMIT_Q					
	"SESSION",									// 111 SURF_MSG_SESSION						
	"TIME?",									// 112 SURF_MSG_TIME_Q							
	"WAVE TIME",								// 113 SURF_MSG_WAVE_TIME						
	"SELECT RIDER",								// 114 SURF_MSG_SELECT_RIDER					
	"MARK",										// 115 SURF_MSG_MARK							
	"SUMMER",									// 116 SURF_MSG_SUMMER							
	"CRYSTAL",									// 117 SURF_MSG_CRYSTAL						
	"CAM",										// 118 SURF_MSG_CAM							
	"BEAR",										// 119 SURF_MSG_BEAR							
	"TANIA",									// 120 SURF_MSG_TANIA							
	"CHOOK",									// 121 SURF_MSG_CHOOK							
	"JAIMIE",									// 122 SURF_MSG_JAIMIE							
	"SELECT CRAFT",								// 123 SURF_MSG_SELECT_CRAFT					
	"SELECT BEACH",								// 124 SURF_MSG_SELECT_BEACH					
	"LAGUNA BEACH",								// 125 SURF_MSG_LAGUNA_BEACH					
	"SAN DIEGO",								// 126 SURF_MSG_SAN_DIEGO						
	"TORREY PINE",								// 127 SURF_MSG_TORREY_PINE					
	"BIG SUR COAST",							// 128 SURF_MSG_BIG_SUR_COAST					
	"SANTA CRUZ",								// 129 SURF_MSG_SANTA_CRUZ						
	"SONOMA COAST",								// 130 SURF_MSG_SONOMA_COAST					
	"FORT BRAGG",								// 131 SURF_MSG_FORT_BRAGG						
	"MALIBU",									// 132 SURF_MSG_MALIBU							
	"SELECT BOARD",								// 133 SURF_MSG_SELECT_BOARD					
	"P",										// 134 SURF_MSG_P								
	"TEST MODE MENU",							// 135 SURF_MSG_TEST_MODE_MENU					
	"PLAYER",									// 136 SURF_MSG_PLAYER							
	"READY?",									// 137 SURF_MSG_READY_Q						
	"PRESS  ",									// 138 SURF_MSG_PRESS__						
	"ARE YOU SURE?",							// 139 SURF_MSG_ARE_YOU_SURE_Q					
	"SAVE GAME STATE?",							// 140 SURF_MSG_SAVE_GAME_STATE_Q				
	"SAVE GAME STATE",							// 141 SURF_MSG_SAVE_GAME_STATE				
	"YES",										// 142 SURF_MSG_YES							
	"NO",										// 143 SURF_MSG_NO								
	"ON",										// 144 SURF_MSG_ON								
	"OFF",										// 145 SURF_MSG_OFF							
	"BIG AIR RESULTS",							// 146 SURF_MSG_BIG_AIR_RESULTS				
	"NAME",										// 147 SURF_MSG_NAME							
	"HEIGHT",									// 148 SURF_MSG_HEIGHT							
	"PLACE",									// 149 SURF_MSG_PLACE							
	"BIG AIR WINNER",							// 150 SURF_MSG_BIG_AIR_WINNER					
	"CONGRATULATIONS",							// 151 SURF_MSG_CONGRATULATIONS				
	"PLAY AGAIN?",								// 152 SURF_MSG_PLAY_AGAIN_Q					
	"SCORE",									// 153 SURF_MSG_SCORE							
	"BEACH CONTEST RESULTS",					// 154 SURF_MSG_BEACH_CONTEST_RESULTS			
	"RIDER CHAMPIONSHIP RESULTS",				// 155 SURF_MSG_RIDER_CHAMPIONSHIP_RESULTS		
	"CHAMPIONSHIP BEACH WINNER",				// 156 SURF_MSG_CHAMPIONSHIP_BEACH_WINNER		
	"BEACH CONTEST WINNER",						// 157 SURF_MSG_BEACH_CONTEST_WINNER			
	"POINTS",									// 158 SURF_MSG_POINTS							
	"CHAMPIONSHIP PLACINGS",					// 159 SURF_MSG_CHAMPIONSHIP_PLACINGS			
	"CHAMPIONSHIP WINNER",						// 160 SURF_MSG_CHAMPIONSHIP_WINNER			
	"EXTREME TRICK RESULTS",					// 161 SURF_MSG_EXTREME_TRICK_RESULTS			
	"EXTREME TRICK WINNER",						// 162 SURF_MSG_EXTREME_TRICK_WINNER			
	"JUDGES SCORE?",							// 163 SURF_MSG_JUDGES_SCORE_Q					
	"WAVE SCORE",								// 164 SURF_MSG_WAVE_SCORE						
	"NEXT BEACH",								// 165 SURF_MSG_NEXT_BEACH						
	"SAVE GAME",								// 166 SURF_MSG_SAVE_GAME						
	"SHOW PLACINGS",							// 167 SURF_MSG_SHOW_PLACINGS					
	"BEST",										// 168 SURF_MSG_BEST							
	"HIGHEST",									// 169 SURF_MSG_HIGHEST						
	"CURRENT",									// 170 SURF_MSG_CURRENT						
	"AIR",										// 171 SURF_MSG_AIR							
	"SCORE 1",									// 172 SURF_MSG_BEST_SCORE_1					
	"SCORE 2",									// 173 SURF_MSG_BEST_SCORE_2					
	"SCORE 3",									// 174 SURF_MSG_BEST_SCORE_3					
	" 0.00",									// 175 SURF_MSG_ZERO_POINT_ZERO_ZERO			
	"CONTEST",									// 176 SURF_MSG_CONTEST						
	"CHAMPIONSHIP",								// 177 SURF_MSG_CHAMPIONSHIP					
	"EXTREME",									// 178 SURF_MSG_EXTREME						
	"REPLAY",									// 179 SURF_MSG_REPLAY							
	"DEMO",										// 180 SURF_MSG_DEMO							
	"GRAPHICS",									// 181 SURF_MSG_GRAPHICS						
	"CUTBACK",									// 182 SURF_MSG_CUTBACK						
	"FORWARD SPIN",								// 183 SURF_MSG_FORWARD_SPIN					
	"REVERSE SPIN",								// 184 SURF_MSG_REVERSE_SPIN					
	"AIR ROLL",									// 185 SURF_MSG_AIR_ROLL						
	"EL ROLLO",									// 186 SURF_MSG_EL_ROLLO						
	"BARREL ROLL",								// 187 SURF_MSG_BARREL_ROLL					
	"INVERTED AIR",								// 188 SURF_MSG_INVERTED_AIR					
	"AIR FORWARD SPIN",							// 189 SURF_MSG_AIR_FORWARD_SPIN				
	"AIR REVERSE SPIN",							// 190 SURF_MSG_AIR_REVERSE_SPIN				
	"AIR ROLL SPIN",							// 191 SURF_MSG_AIR_ROLL_SPIN					
	"BACKFLIP",									// 192 SURF_MSG_BACKFLIP						
	"FRONTFLIP",								// 193 SURF_MSG_FRONTFLIP						
	"DOUBLE AIR ROLL",							// 194 SURF_MSG_DOUBLE_AIR_ROLL				
	"DOUBLE EL ROLLO",							// 195 SURF_MSG_DOUBLE_EL_ROLLO				
	"DOUBLE BARREL ROLL",						// 196 SURF_MSG_DOUBLE_BARREL_ROLL				
	"DOUBLE REVERSE AIR",						// 197 SURF_MSG_DOUBLE_REVERSE_AIR				
	"DOUBLE FORWARD AIR",						// 198 SURF_MSG_DOUBLE_FORWARD_AIR				
	"UNKNOWN",									// 199 SURF_MSG_UNKNOWN						
	"JETRACER",									// 200 SURF_MSG_JETRACER
	"REENTRY",									// 201 SURF_MSG_REENTRY						
	"AIR REENTRY",								// 202 SURF_MSG_AIR_REENTRY					
	"THREE SIXTY",								// 203 SURF_MSG_THREE_SIXTY					
	"BOTTOM HAND TURN",							// 204 SURF_MSG_BOTTOM_HAND_TURN				
	"VOLUME",									// 205 SURF_MSG_VOLUME							
	"BARREL RIDE!",								// 206 SURF_MSG_BARREL_RIDE					
	"FRONT AIR THREE SIXTY",					// 207 SURF_MSG_FRONT_AIR_360					
	"BACK AIR THREE SIXTY",						// 208 SURF_MSG_BACK_AIR_360					
	"FRONT AIR SEVEN TWENTY",					// 209 SURF_MSG_FRONT_AIR_720					
	"BACK AIR SEVEN TWENTY",					// 210 SURF_MSG_BACK_AIR_720					
	"SUPERMAN!",								// 211 SURF_MSG_SUPERMAN						
	"AIR ONE EIGHTY",							// 212 SURF_MSG_AIR_180						
	"BRONCO AIR ONE EIGHTY",					// 213 SURF_MSG_BRONCO_AIR_180					
	"WHITE HOT",								// 214 SURF_MSG_WHITE_HOT						
	"LEAP FROG",								// 215 SURF_MSG_LEAP_FROG						
	"THE DART",									// 216 SURF_MSG_THE_DART						
	"WAVE JUMPER",								// 217 SURF_MSG_WAVE_JUMPER					
	"OCEAN BLUE",								// 218 SURF_MSG_OCEAN_BLUE						
		"WAVE RIDER",							// 219 SURF_MSG_WAVE_RIDER						
	"FREE RIDE",								// 220 SURF_MSG_FREE_RIDE						
	"BUMP N JUMP",								// 221 SURF_MSG_BUMP_N_JUMP					
	"SLASH",									// 222 SURF_MSG_SLASH							
	"YELLOW CURL",								// 223 SURF_MSG_YELLOW_CURL							
	"PACIFIC BLUE",								// 224 SURF_MSG_PACIFIC_BLUE					
	"QUICK SNAP",								// 225 SURF_MSG_QUICK_SNAP						
	"STYLE RIDER",								// 226 SURF_MSG_STYLE_RIDER					
	"REDBACK",									// 227 SURF_MSG_REDBACK						
	"SHARK TOOTH",								// 228 SURF_MSG_SHARK_TOOTH					
	"SUNSET",									// 229 SURF_MSG_SUNSET							
	"PINE LIME",								// 230 SURF_MSG_PINE_LIME						
	"SWISH",									// 231 SURF_MSG_SWISH							
	"POISON TIP",								// 232 SURF_MSG_POISON_TIP						
	"-",										// 233 SURF_MSG_UNUSED_3
	"TUBES RULE",								// 234 SURF_MSG_TUBES_RULE						
	"FLAME OUT",								// 235 SURF_MSG_FLAME_OUT						
	"RAINBOW",									// 236 SURF_MSG_RAINBOW						
	"IN ZONE",									// 237 SURF_MSG_IN_ZONE						
	"CONCEPT",									// 238 SURF_MSG_CONCEPT						
	"SWIFT",									// 239 SURF_MSG_SWIFT							
	"CANNIBAL",									// 240 SURF_MSG_CANNIBAL						
	"DART",										// 241 SURF_MSG_DART							
	"DEVIL_RAY",								// 242 SURF_MSG_DEVIL_RAY						
	"PRO X5T",									// 243 SURF_MSG_PRO_X5T						
	"MIRAGE IV",								// 244 SURF_MSG_MIRAGE_IV						
	"SABRE PRO",								// 245 SURF_MSG_SABRE_PRO						
	"WINGNUT",									// 246 SURF_MSG_WINGNUT						
	"TYPHOON",									// 247 SURF_MSG_TYPHOON						
	"CYCLONE",									// 248 SURF_MSG_CYCLONE						
	"HURRICANE",								// 249 SURF_MSG_HURRICANE							
	"BEACH CAM",								// 250 SURF_MSG_BEACH_CAM						
	"BOAT CAM",									// 251 SURF_MSG_BOAT_CAM						
	"LIGHTHOUSE CAM",							// 252 SURF_MSG_LIGHTHOUSE_CAM					
	"TUBE CAM",									// 253 SURF_MSG_TUBE_CAM						
	"BARREL CAM",								// 254 SURF_MSG_BARREL_CAM						
	"SEAGULL CAM",								// 255 SURF_MSG_SEAGULL_CAM					
	"LOCKED",									// 256 SURF_MSG_LOCKED							
	"ALL BEACHES MUST",							// 257 SURF_MSG_ALL_BEACHES_MUST				
	"BE UNLOCKED",								// 258 SURF_MSG_BE_UNLOCKED					
	"TO PLAY THIS",								// 259 SURF_MSG_TO_PLAY_THIS					
	"GAME",										// 260 SURF_MSG_GAME							
	"YOU HAVE UNLOCKED",						// 261 SURF_MSG_YOU_HAVE_UNLOCKED				
	"THE BEACH",								// 262 SURF_MSG_THE_BEACH						
	"HIGHEST AIR",								// 263 SURF_MSG_HIGHEST_AIR					
	"EXTREME SCORE",							// 264 SURF_MSG_EXTREME_SCORE					
	"DIFFICULTY",								// 265 SURF_MSG_DIFFICULTY						
	"RIDER SKILL",								// 266 SURF_MSG_RIDER_SKILL					
	"KOOK",										// 267 SURF_MSG_KOOK							
	"AMATEUR",									// 268 SURF_MSG_AMATEUR						
	"PRO",										// 269 SURF_MSG_PRO							
	"WIN 1 PLAYER",								// 270 SURF_MSG_WIN_1_PLAYER					
	"TO UNLOCK",								// 271 SURF_MSG_TO_UNLOCK						
	"THIS BEACH",								// 272 SURF_MSG_THIS_BEACH						
	"760CC SIT DOWN",							// 273 SURF_MSG_WAVEBLASTER_WB760				
	"800CC SIT DOWN",							// 274 SURF_MSG_WAVEBLASTER_WB800				
	"700CC STAND UP",							// 275 SURF_MSG_SUPERJET_700					
	"800CC SIT DOWN",							// 276 SURF_MSG_WAVERUNNER_GP800				
	"1200CC SIT DOWN",							// 277 SURF_MSG_WAVERUNNER_GP1200R
	"LANGUAGE: ENGLISH",						// 278 SURF_MSG_SELECT_LANGUAGE
	"SELECT CRAFT",								// 279 SURF_MSG_SELECT_WATERCRAFT
	"ON THE MEMORY CARD",						// 280 SURF_MSG_ON_THE_MEMORY_CARD			
	"REPLAY ON THE",							// 281 SURF_MSG_REPLAY_ON_THE
};

static char *german_text[] = {
	" ",										//   0 SURF_MSG_BLANK
	"LADEVORGANG...",							//   1 SURF_MSG_LOADING
	"START DRU\133CKEN",						//   2 SURF_MSG_PRESS_START
	"MEMORY CARD WIRD U\133BERPRU\133FT",		//   3 SURF_MSG_CHECKING_MEMORY_CARD
	"DU KANNST NUR SPEILE",						//   4 SURF_MSG_YOU_WILL_NOT_BE_ABLE_TO_SAVE
	"SPEICHERN WENN DU EINE",					//   5 SURF_MSG_ANY_GAMES_UNLESS_YOU_INSERT_A	
	"MEMORY CARD IN DEN",						//   6 SURF_MSG_MEMORY_CARD_INTO_THE
	"MEMORY CARD STECKPLATZ EINLEGST",			//*  7 SURF_MSG_MEMORY_CARD_SLOT_INSERT
	"WEITER",									//   8 SURF_MSG_CONTINUE						
	"ERNEUT VERSUCHEN",							//   9 SURF_MSG_TRY_AGAIN						
	"MEMORY CARD IST",							//  10 SURF_MSG_MEMORY_CARD_IS					
	"NICHT EINGELEGT IN",						//  11 SURF_MSG_NOT_INSERTED_INTO				
	"DIE MEMORY CARD",							//  12 SURF_MSG_THE_MEMORY_CARD				
	"STECKPLATZ...",							//  13 SURF_MSG_SLOT							
	"ZU U\133BERSCHREIBENDE",					//  14 SURF_MSG_TO_OVERWRITE
	"NICHT GENU\133GEND",						//  15 SURF_MSG_INSUFFICIENT					
	"FREIE SPEICHERBLO\133CKE",					//  16 SURF_MSG_FREE_BLOCKS					
	"VERFU\133GBAR",							//* 17 SURF_MSG_AVAILABLE					
	"ZU U\133BERSCHREIBENDES",					//* 18 SURF_MSG_TO_OVERWRITEG
	"FEHLER BEIM",								//  19 SURF_MSG_ERROR_WHEN						
	"VERWENDEN DER",							//* 20 SURF_MSG_USING_THE				
	"CARD",										//  21 SURF_MSG_CARD							
	"GELADEN",									//* 22 SURF_MSG_IS_LOADING					
	"DATENFEHLER IN",							//  23 SURF_MSG_DATA_ERROR						
	"GESPEICHERTER",							//  24 SURF_MSG_IN_THE_SAVED					
	"WEIDERHOLUNGSDATEI",						//  25 SURF_MSG_REPLAY_FILE					
	"SPIELDATEI",								//  26 SURF_MSG_GAME_FILE						
	"KEINE GESPEICHERTEN",						//  27 SURF_MSG_THERE_ARE_NO					
	" ",										//  28 SURF_MSG_				
	"AUF DER",									//* 29 SURF_MSG_ON_THE
	"MEMORY CARD",								//  30 SURF_MSG_MEMORY_CARD					
	" ",										//  31 SURF_MSG_
	"SPIEL WIRD VON",							//* 32 SURF_MSG_GAME_ON_THE
	" ",										//  33 SURF_MSG_
	" ",										//  34 SURF_MSG_
	"GELO\133SCHT",								//* 35 SURF_MSG_IS_DELETING
	" ",										//  36 SURF_MSG_
	"FORMATIERUNG DER",							//* 37 SURF_MSG_FORMAT_OF
	"ABGESCHLOSSEN",							//  38 SURF_MSG_COMPLETED						
	"GESCHEITERT",								//  39 SURF_MSG_FAILED							
	"NICHT FORMATIERT",							//  40 SURF_MSG_UNFORMATTED
	"JETZT FORMATIEREN?",						//  41 SURF_MSG_FORMAT_NOW_Q					
	"WIRD FORMATIERT",							//  42 SURF_MSG_FORMATTING						
	"BITTE WARTEN...",							//  43 SURF_MSG_PLEASE_WAIT					
	"MAXIMALE",									//  44 SURF_MSG_THE_MAXIMUM					
	"ZAHL DER",									//  45 SURF_MSG_NUMBER_OF						
	"SPEILDATEIEN",								//  46 SURF_MSG_GAME_FILES						
	"WIEDERHOLUNGSDATEIEN",						//  47 SURF_MSG_REPLAY_FILES					
	"WURDE GESPEICHERT",						//  48 SURF_MSG_HAVE_BEEN_SAVED				
	"GESPEICHERT",								//* 49 SURF_MSG_IS_SAVING, SURF_MSG_SAVED
	"ZAHL AN",									//* 50 SURF_MSG_NUMBER_OF_THE
	"SPEICHERN ABBRECHEN",						//  51 SURF_MSG_CANCEL_SAVE					
	"ABBRECHEN",								//  52 SURF_MSG_CANCEL							
	"WIRD U\133BERPRU\133FT",					//  53 SURF_MSG_CHECKING						
	"DAS SPIEL",								//  54 SURF_MSG_THE_GAME						
	"DIE WIEDERHOLUNG",							//  55 SURF_MSG_THE_REPLAY						
	"WURDE AUF DE",								//* 56 SURF_MSG_IS_ON_THE			
	"ZU LADENDES",								//* 57 SURF_MSG_TO_LOADG
	"WASSERSPORTARTEN",							//  58 SURF_MSG_WATER_SPORTS					
	"SPIELSTATUS",								//  59 SURF_MSG_GAME_STATE						
	"SPIEL STARTEN",							//  60 SURF_MSG_START_GAME						
	"MIT BELIEBIGER TASTE BEENDEN",				//  61 SURF_MSG_PRESS_ANY_BUTTON_TO_QUIT		
	"WIEDERHOLUNG NUMMER",						//  62 SURF_MSG_REPLAY_NUMBER					
	"SPIEL NUMMER",								//  63 SURF_MSG_GAME_NUMBER					
	"SPIEL LADEN",								//  64 SURF_MSG_LOAD_GAME						
	"MEISTERSCHAFT LADEN",						//  65 SURF_MSG_LOAD_CHAMPIONSHIP				
	"WIEDERHOLUNG LADEN",						//  66 SURF_MSG_LOAD_REPLAY					
	"SPIEL AUSWA\133HLEN",						//  67 SURF_MSG_SELECT_GAME					
	"WIEDERHOLUNG AUSWA\133HLEN",				//  68 SURF_MSG_SELECT_REPLAY					
	"ZU LADENDE",								//  69 SURF_MSG_TO_LOAD						
	"OPTIONEN",									//  70 SURF_MSG_OPTIONS						
	"BEENDEN",									//  71 SURF_MSG_QUIT							
	"WIEDER AUFNEHMEN",							//  72 SURF_MSG_RESUME							
	"BEWERTUNG",								//  73 SURF_MSG_JUDGING						
	"SOFORTIGE WIEDERHOLUNG",					//  74 SURF_MSG_INSTANT_REPLAY					
	"WIEDERHOLUNG SPEICHERN",					//  75 SURF_MSG_SAVE_REPLAY					
	"ALS NEU SPEICHERN",						//  76 SURF_MSG_SAVE_AS_NEW					
	"U\133BERSCHREIBEN",						//  77 SURF_MSG_OVERWRITE						
	"ZEITLUPENSPRUNG",							//  78 SURF_MSG_SLOMO_AIR						
	"BILDSCHIRM EINSTELLEN",					//  79 SURF_MSG_ADJUST_SCREEN					
	"SOUND",									//  80 SURF_MSG_SOUND							
	"MUSIK",									//  81 SURF_MSG_MUSIC							
	"AUSWA\133HLEN",							//  82 SURF_MSG_SELECT							
	"ZURU\133CK",								//  83 SURF_MSG_GO_BACK						
	"KEIN CONTROLLER",							//  84 SURF_MSG_CONTROLLER_REMOVED
	"EINLEGEN",									//  85 SURF_MSG_THE_CONTROLLER			
	"PRO BODYBOARDING",							//  86 SURF_MSG_PRO_BODYBOARDING
	"SPIEL BEENDEN?",							//  87 SURF_MSG_QUIT_GAME_Q
	"BITTE CONTROLLER",							//  88 SURF_MSG_PLEASE_REINSERT				
	"IN CONTROLLER",							//  89 SURF_MSG_A_CONTROLLER_INTO				
	"ANSCHLUSS 1 ANSCHLIESSEN",					//  90 SURF_MSG_CONTROLLER_PORT_1				
	"WEITER MIT START",							//  91 SURF_MSG_PRESS_START_TO_CONTINUE		
	"CONTROLLER ANSCHLUSS",						//  92 SURF_MSG_CONTROLLER_PORT							
	"TRAININGSMODUS",							//  93 SURF_MSG_FREERIDE						
	"GETEILTER BILDSCHIRM",						//  94 SURF_MSG_SPLIT_SCREEN					
	"BIG AIR",									//  95 SURF_MSG_BIG_AIR						
	"STRANDWETTBEWERB",							//  96 SURF_MSG_BEACH_CONTEST					
	"SPORTLERMEISTERSCHAFT",					//  97 SURF_MSG_RIDER_CHAMPIONSHIP				
	"EXTREMTRICK",								//  98 SURF_MSG_EXTREME_TRICK					
	"SPORT AUSWA\133HLEN",						//  99 SURF_MSG_SELECT_SPORT					
	"SURFEN",									// 100 SURF_MSG_SURFING						
	"WASSERJET",								// 101 SURF_MSG_JET_WATERCRAFT					
	"WINDSURFEN",								// 102 SURF_MSG_WINDSURFING					
	"BODYBOARDING",								// 103 SURF_MSG_BODYBOARD_RIDING				
	"BILDSCHIRM ZENTRIEREN",					// 104 SURF_MSG_CENTRE_SCREEN					
	"STEUERUNG",								// 105 SURF_MSG_CONTROLS						
	"VIBRATION",								// 106 SURF_MSG_VIBRATION						
	"BIG AIR-WETTBEWERB",						// 107 SURF_MSG_BIG_AIR_COMPETITION				
	"SPIELER?",									// 108 SURF_MSG_PLAYERS_Q						
	"MAX WARTEZEIT",							// 109 SURF_MSG_CATCH_A_WAVE					
	"AUF WELLE?",								// 110 SURF_MSG_TIME_LIMIT_Q					
	"AUFGEHOBEN",								//*111 SURF_MSG_UNLOCKED
	"SITZUNGSDAUER?",							// 112 SURF_MSG_TIME_Q							
	"WELLENREITZEIT",							// 113 SURF_MSG_WAVE_TIME						
	"WELLENREITER AUSWA\133HLEN",				// 114 SURF_MSG_SELECT_RIDER					
	"MARK",										// 115 SURF_MSG_MARK							
	"SUMMER",									// 116 SURF_MSG_SUMMER							
	"CRYSTAL",									// 117 SURF_MSG_CRYSTAL						
	"CAM",										// 118 SURF_MSG_CAM							
	"BEAR",										// 119 SURF_MSG_BEAR							
	"TANIA",									// 120 SURF_MSG_TANIA							
	"CHOOK",									// 121 SURF_MSG_CHOOK							
	"JAIMIE",									// 122 SURF_MSG_JAIMIE							
	"BOOT AUSWA\133HLEN",						// 123 SURF_MSG_SELECT_CRAFT					
	"STRAND AUSWA\133HLEN",						// 124 SURF_MSG_SELECT_BEACH					
	"LAGUNA BEACH",								// 125 SURF_MSG_LAGUNA_BEACH					
	"SAN DIEGO",								// 126 SURF_MSG_SAN_DIEGO						
	"TORREY PINE",								// 127 SURF_MSG_TORREY_PINE					
	"BIG SUR COAST",							// 128 SURF_MSG_BIG_SUR_COAST					
	"SANTA CRUZ",								// 129 SURF_MSG_SANTA_CRUZ						
	"SONOMA COAST",								// 130 SURF_MSG_SONOMA_COAST					
	"FORT BRAGG",								// 131 SURF_MSG_FORT_BRAGG						
	"MALIBU",									// 132 SURF_MSG_MALIBU							
	"BOARD AUSWA\133HLEN",						// 133 SURF_MSG_SELECT_BOARD					
	"S",										// 134 SURF_MSG_P								
	"MENU\133 TESTMODUS",						// 135 SURF_MSG_TEST_MODE_MENU					
	"SPIELER",									// 136 SURF_MSG_PLAYER							
	"BERREIT?",									// 137 SURF_MSG_READY_Q						
	"DRU\133CKEN    ",							// 138 SURF_MSG_PRESS__						
	"SICHER?",									// 139 SURF_MSG_ARE_YOU_SURE_Q					
	"SPIELSTATUS SPEICHERN?",					// 140 SURF_MSG_SAVE_GAME_STATE_Q				
	"SPIELSTATUS SPEICHERN",					// 141 SURF_MSG_SAVE_GAME_STATE				
	"JA",										// 142 SURF_MSG_YES							
	"NEIN",										// 143 SURF_MSG_NO								
	"EIN",										// 144 SURF_MSG_ON								
	"AUS",										// 145 SURF_MSG_OFF							
	"BIG AIR-ERGEBNISSE",						// 146 SURF_MSG_BIG_AIR_RESULTS				
	"NAME",										// 147 SURF_MSG_NAME							
	"GRO\133SSE",								// 148 SURF_MSG_HEIGHT							
	"ORT",										// 149 SURF_MSG_PLACE							
	"BIG AIR-GEWINNER",							// 150 SURF_MSG_BIG_AIR_WINNER					
	"GLU\133CKWUNSCH",							// 151 SURF_MSG_CONGRATULATIONS				
	"NOCH EINMAL SPIELEN?",						// 152 SURF_MSG_PLAY_AGAIN_Q					
	"PUNKTBEWERTUNG",							// 153 SURF_MSG_SCORE							
	"ERGEBNISSE DES STRANDWETTBEWERBS",			// 154 SURF_MSG_BEACH_CONTEST_RESULTS			
	"SPORTLERMEISTERSCHAFTSERGEBNISSE",			// 155 SURF_MSG_RIDER_CHAMPIONSHIP_RESULTS		
	"SIEGER DER STRANDMEISTERSCHAFT",			// 156 SURF_MSG_CHAMPIONSHIP_BEACH_WINNER		
	"SIEGER DES STRANDWETTBEWERBS",				// 157 SURF_MSG_BEACH_CONTEST_WINNER			
	"GESAMTPUNKTE",								// 158 SURF_MSG_POINTS							
	"MEISTERSCHAFTPLATZIERUNGEN",				// 159 SURF_MSG_CHAMPIONSHIP_PLACINGS			
	"MEISTERSCHAFTSSEIGER",						// 160 SURF_MSG_CHAMPIONSHIP_WINNER			
	"EXTREMTRICK-ERGEBNISSE",					// 161 SURF_MSG_EXTREME_TRICK_RESULTS			
	"SIEGER DER EXTREMTRICKS",					// 162 SURF_MSG_EXTREME_TRICK_WINNER			
	"RICHTERPUNKTZAHL?",						// 163 SURF_MSG_JUDGES_SCORE_Q					
	"WELLENPUNKTZAHL",							// 164 SURF_MSG_WAVE_SCORE						
	"NA\133CHSTER STRAND",						// 165 SURF_MSG_NEXT_BEACH						
	"SPIEL SPEICHERN",							// 166 SURF_MSG_SAVE_GAME						
	"PLATZIERUNGEN ZEIGEN",						// 167 SURF_MSG_SHOW_PLACINGS					
	"BESTE",									// 168 SURF_MSG_BEST							
	"HO\133CHSTE",								// 169 SURF_MSG_HIGHEST						
	"AKTUELLE",									// 170 SURF_MSG_CURRENT						
	"IN DER LUFT",								// 171 SURF_MSG_AIR							
	"PUNKTZAHL 1",								// 172 SURF_MSG_BEST_SCORE_1					
	"PUNKTZAHL 2",								// 173 SURF_MSG_BEST_SCORE_2					
	"PUNKTZAHL 3",								// 174 SURF_MSG_BEST_SCORE_3					
	" 0.00",									// 175 SURF_MSG_ZERO_POINT_ZERO_ZERO			
	"WETTKAMPF",								// 176 SURF_MSG_CONTEST						
	"MEISTERSCHAFT",							// 177 SURF_MSG_CHAMPIONSHIP					
	"EXTREM",									// 178 SURF_MSG_EXTREME						
	"WIEDERHOLUNG",								// 179 SURF_MSG_REPLAY							
	"DEMO",										// 180 SURF_MSG_DEMO							
	"GRAFIKEN",									// 181 SURF_MSG_GRAPHICS						
	"CUTBACK",									// 182 SURF_MSG_CUTBACK						
	"FORWARD SPIN",								// 183 SURF_MSG_FORWARD_SPIN					
	"REVERSE SPIN",								// 184 SURF_MSG_REVERSE_SPIN					
	"AIR ROLL",									// 185 SURF_MSG_AIR_ROLL						
	"EL ROLLO",									// 186 SURF_MSG_EL_ROLLO						
	"BARREL ROLL",								// 187 SURF_MSG_BARREL_ROLL					
	"INVERTED AIR",								// 188 SURF_MSG_INVERTED_AIR					
	"AIR FORWARD SPIN",							// 189 SURF_MSG_AIR_FORWARD_SPIN				
	"AIR REVERSE SPIN",							// 190 SURF_MSG_AIR_REVERSE_SPIN				
	"AIR ROLL SPIN",							// 191 SURF_MSG_AIR_ROLL_SPIN					
	"BACKFLIP",									// 192 SURF_MSG_BACKFLIP						
	"FRONTFLIP",								// 193 SURF_MSG_FRONTFLIP						
	"DOUBLE AIR ROLL",							// 194 SURF_MSG_DOUBLE_AIR_ROLL				
	"DOUBLE EL ROLLO",							// 195 SURF_MSG_DOUBLE_EL_ROLLO				
	"DOUBLE BARREL ROLL",						// 196 SURF_MSG_DOUBLE_BARREL_ROLL				
	"DOUBLE REVERSE AIR",						// 197 SURF_MSG_DOUBLE_REVERSE_AIR				
	"DOUBLE FORWARD AIR",						// 198 SURF_MSG_DOUBLE_FORWARD_AIR				
	"UNBEKANNT",								// 199 SURF_MSG_UNKNOWN						
	"JETRACER",									// 200 SURF_MSG_JETRACER
	"REENTRY",									// 201 SURF_MSG_REENTRY						
	"AIR REENTRY",								// 202 SURF_MSG_AIR_REENTRY					
	"THREE SIXTY",								// 203 SURF_MSG_THREE_SIXTY					
	"BOTTOM HAND TURN",							// 204 SURF_MSG_BOTTOM_HAND_TURN				
	"LAUTSTA\133RKE",							// 205 SURF_MSG_VOLUME							
	"BARREL RIDE!",								// 206 SURF_MSG_BARREL_RIDE					
	"FRONT AIR THREE SIXTY",					// 207 SURF_MSG_FRONT_AIR_360					
	"BACK AIR THREE SIXTY",						// 208 SURF_MSG_BACK_AIR_360					
	"FRONT AIR SEVEN TWENTY",					// 209 SURF_MSG_FRONT_AIR_720					
	"BACK AIR SEVEN TWENTY",					// 210 SURF_MSG_BACK_AIR_720					
	"SUPERMANN!",								// 211 SURF_MSG_SUPERMAN						
	"AIR ONE EIGHTY",							// 212 SURF_MSG_AIR_180						
	"BRONCO AIR ONE EIGHTY",					// 213 SURF_MSG_BRONCO_AIR_180					
	"WHITE HOT",								// 214 SURF_MSG_WHITE_HOT						
	"LEAP FROG",								// 215 SURF_MSG_LEAP_FROG						
	"THE DART",									// 216 SURF_MSG_THE_DART						
	"WAVE JUMPER",								// 217 SURF_MSG_WAVE_JUMPER					
	"OCEAN BLUE",								// 218 SURF_MSG_OCEAN_BLUE						
	"WAVE RIDER",								// 219 SURF_MSG_WAVE_RIDER						
	"FREE RIDE",								// 220 SURF_MSG_FREE_RIDE						
	"BUMP N JUMP",								// 221 SURF_MSG_BUMP_N_JUMP					
	"SLASH",									// 222 SURF_MSG_SLASH							
	"YELLOW CURL",								// 223 SURF_MSG_YELLOW_CURL							
	"PACIFIC BLUE",								// 224 SURF_MSG_PACIFIC_BLUE					
	"QUICK SNAP",								// 225 SURF_MSG_QUICK_SNAP						
	"STYLE RIDER",								// 226 SURF_MSG_STYLE_RIDER					
	"REDBACK",									// 227 SURF_MSG_REDBACK						
	"SHARK TOOTH",								// 228 SURF_MSG_SHARK_TOOTH					
	"SUNSET",									// 229 SURF_MSG_SUNSET							
	"PINE LIME",								// 230 SURF_MSG_PINE_LIME						
	"SWISH",									// 231 SURF_MSG_SWISH							
	"POISON TIP",								// 232 SURF_MSG_POISON_TIP						
	"MUSS 1 SPIELER-",							//*233 SURF_MSG_MUST_WIN
	"TUBES RULE",								// 234 SURF_MSG_TUBES_RULE						
	"FLAME OUT",								// 235 SURF_MSG_FLAME_OUT						
	"RAINBOW",									// 236 SURF_MSG_RAINBOW						
	"IN ZONE",									// 237 SURF_MSG_IN_ZONE						
	"CONCEPT",									// 238 SURF_MSG_CONCEPT						
	"SWIFT",									// 239 SURF_MSG_SWIFT							
	"CANNIBAL",									// 240 SURF_MSG_CANNIBAL						
	"DART",										// 241 SURF_MSG_DART							
	"DEVIL_RAY",								// 242 SURF_MSG_DEVIL_RAY						
	"PRO X5T",									// 243 SURF_MSG_PRO_X5T						
	"MIRAGE IV",								// 244 SURF_MSG_MIRAGE_IV						
	"SABRE PRO",								// 245 SURF_MSG_SABRE_PRO						
	"WINGNUT",									// 246 SURF_MSG_WINGNUT						
	"TYPHOON",									// 247 SURF_MSG_TYPHOON						
	"CYCLONE",									// 248 SURF_MSG_CYCLONE						
	"HURRICANE",								// 249 SURF_MSG_HURRICANE							
	"STRANDKAMERA",								// 250 SURF_MSG_BEACH_CAM						
	"BOOTKAMERA",								// 251 SURF_MSG_BOAT_CAM						
	"LEUCHTTURMKAMERA",							// 252 SURF_MSG_LIGHTHOUSE_CAM					
	"TUBE-KAMERA",								// 253 SURF_MSG_TUBE_CAM						
	"BARREL-KAMERA",							// 254 SURF_MSG_BARREL_CAM						
	"MO\133VENSICHT",							// 255 SURF_MSG_SEAGULL_CAM					
	"GESPERRT",									// 256 SURF_MSG_LOCKED							
	"ALLE STRANDSPERREN",						// 257 SURF_MSG_ALL_BEACHES_MUST				
	"MU\133SSEN AUFGEHOBEN",					// 258 SURF_MSG_BE_UNLOCKED					
	"WERDEN UM SPEIL",							// 259 SURF_MSG_TO_PLAY_THIS					
	"ZU STARTEN",								// 260 SURF_MSG_GAME							
	"DU HAST DIE",								// 261 SURF_MSG_YOU_HAVE_THE
	"STRANDSPERRE",								// 262 SURF_MSG_LOCKED_BEACH						
	"HO\133CHSTER AIRTRICK",					// 263 SURF_MSG_HIGHEST_AIR					
	"EXTREMPUNKTZAHL",							// 264 SURF_MSG_EXTREME_SCORE					
	"SCHWIERIGKEIT FU\133R",					// 265 SURF_MSG_DIFFICULTY						
	"WELLENREITERKONNEN FU\133R",				// 266 SURF_MSG_RIDER_SKILL					
	"SPINNER",									// 267 SURF_MSG_KOOK							
	"AMATEUR",									// 268 SURF_MSG_AMATEUR						
	"PROFI",									// 269 SURF_MSG_PRO							
	"FU\133R DEISEN STRAND",					//*270 SURF_MSG_TO_OPEN_BEACH
	"GEWONNEN WERDEN",							// 271 SURF_MSG_TO_UNLOCK						
	"STRANDWETTKAMPF",							//*272 SURF_MSG_BEACH_GAME
	"760CC SIT DOWN",							// 273 SURF_MSG_WAVEBLASTER_WB760				
	"800CC SIT DOWN",							// 274 SURF_MSG_WAVEBLASTER_WB800				
	"700CC STAND UP",							// 275 SURF_MSG_SUPERJET_700					
	"800CC SIT DOWN",							// 276 SURF_MSG_WAVERUNNER_GP800				
	"1200CC SIT DOWN",							// 277 SURF_MSG_WAVERUNNER_GP1200R				
	"SPRACHE: DUETSCH",							// 278 SURF_MSG_SELECT_LANGUAGE
	"BOOT AUSWA\133HLEN",						// 279 SURF_MSG_SELECT_WATERCRAFT
	"AUF DER MEMORY CARD",						// 280 SURF_MSG_ON_THE_MEMORY_CARD			
	"WIEDERHOLUNG WIRD VON",					// 281 SURF_MSG_REPLAY_ON_THE
};

static char *french_text[] = {
	" ",										//   0 SURF_MSG_BLANK
	"CHARGEMENT...",							//   1 SURF_MSG_LOADING
	"APPUYEZ SUR DEMARRER",						//   2 SURF_MSG_PRESS_START
	"VERIFICATION DE LA CARTE MEMOIRE",			//   3 SURF_MSG_CHECKING_MEMORY_CARD
	"VOUS NE POURREZ PAS ENREGISTRER",			//   4 SURF_MSG_YOU_WILL_NOT_BE_ABLE_TO_SAVE
	"DE PARTIE EN L\134ABSENCE DE CARTE",		//   5 SURF_MSG_ANY_GAMES_UNLESS_YOU_INSERT_A	
	"MEMOIRE DANS LA",							//   6 SURF_MSG_MEMORY_CARD_INTO_THE			
	"FENTE DE CARTE MEMOIRE",					//   7 SURF_MSG_MEMORY_CARD_SLOT				
	"CONTINUER",								//   8 SURF_MSG_CONTINUE						
	"RECOMMENCER",								//   9 SURF_MSG_TRY_AGAIN						
	"PAS DE CARTE MEMOIRE",						//  10 SURF_MSG_MEMORY_CARD_IS					
	"INSEREE DANS LA",							//  11 SURF_MSG_NOT_INSERTED_INTO				
	"DE LA CARTE MEMOIRE",						//  12 SURF_MSG_THE_MEMORY_CARD
	"FENTE DE CARTE",							//* 13 SURF_MSG_SLOT_OF_MEMORY							
	"A REMPLACER",								//  14 SURF_MSG_TO_OVERWRITE					
	"PAS ASSEZ DE",								//  15 SURF_MSG_INSUFFICIENT					
	"BLOCS LIBRES",								//  16 SURF_MSG_FREE_BLOCKS					
	"SUR LA CARTE",								//* 17 SURF_MSG_ON_THE_MEMORY
	"POUR REMPLACER",							//* 18 SURF_MSG_FOR_OVERWRITE
	"ERREUR LORS DE",							//  19 SURF_MSG_ERROR_WHEN
	"L\134UTILISATION",							//* 20 SURF_MSG_USING
	"MEMOIRE",									//  21 SURF_MSG_CARD							
	"SELECTIONNER LA PARTIE",					//* 22 SURF_MSG_SELECT_A_GAME
	"ERREUR DE DONNEES",						//  23 SURF_MSG_DATA_ERROR						
	"DANS LE FICHIER",							//  24 SURF_MSG_IN_THE_SAVED					
	"DE REDIFFUSION",							//  25 SURF_MSG_REPLAY_FILE					
	"DE JEU",									//  26 SURF_MSG_GAME_FILE						
	"PAS DE FICHIERS",							//* 27 SURF_MSG_NO_SAVED
	"SELECTIONNER LA REDIFFUSION",				//* 28 SURF_MSG_SELECT_A_REPLAY
	"ENREGISTRES SUR CETTE",					//* 29 SURF_MSG_ENTRIES_ON_THE					
	"CARTE MEMOIRE",							//  30 SURF_MSG_MEMORY_CARD					
	"REDIFFUSION A PARTIR",						//* 31 SURF_MSG_REPLAY_FROM
	"CHARGEMENT DU JEU",						//  32 SURF_MSG_LOADING_GAME					
	"DEPUIS LA CARTE",							//  33 SURF_MSG_FROM_THE_MEMORY				
	"CHARGEMENT DE LA",							//* 34 SURF_MSG_LOADING_THE					
	"SUPPRESSION DU JEU",						//  35 SURF_MSG_DELETING_GAME					
	"SUPPRESSION DE LA",						//* 36 SURF_MSG_DELETING_THE
	"FORMATAGE DE LA",							//* 37 SURF_MSG_FORMAT_OF_THE
	"ACHEVE",									//  38 SURF_MSG_COMPLETED						
	"ERREUR DE FORMATAGE",						//* 39 SURF_MSG_ERROR_FORMATTING
	"NON FORMATEE",								//* 40 SURF_MSG_NOT_FORMATTED
	"LA FORMATER MAINTENANT?",					//  41 SURF_MSG_FORMAT_NOW_Q					
	"FORMATAGE DE LA",							//  42 SURF_MSG_FORMATTING						
	"PATIENTEZ...",								//  43 SURF_MSG_PLEASE_WAIT					
	"NOMBRE MAXIMUM",							//* 44 SURF_MSG_MAXIMUM_NUMBER				
	"NOMBRE DE",								//  45 SURF_MSG_NUMBER_OF
	"JEU DEJA",									//  46 SURF_MSG_GAME_FILES						
	"REDIFFUSION DEJA",							//  47 SURF_MSG_REPLAY_FILES					
	"ENREGISTRE",								//* 48 SURF_MSG_REGISTERED
	"ENREGISTREMENT",							//* 49 SURF_MSG_SAVING
	"DE LA PARTIE",								//* 50 SURF_MSG_THE_GAME_FILE
	"ANNULER L\134ENREGISTREMENT",				//  51 SURF_MSG_CANCEL_SAVE					
	"ANNULER",									//  52 SURF_MSG_CANCEL							
	"VERIFICATION",								//  53 SURF_MSG_CHECKING						
	"LA PARTIE A",								//  54 SURF_MSG_THE_GAME						
	"LA REDIFFUSION A",							//  55 SURF_MSG_THE_REPLAY						
	"ETE ENREGISTREE",							//  56 SURF_MSG_HAS_BEEN_SAVED					
	"DE FICHIERS DE",							//* 57 SURF_MSG_OF_SAVED
	"SPORTS AQUATIQUES",						//  58 SURF_MSG_WATER_SPORTS					
	"ETAT DU JEU",								//  59 SURF_MSG_GAME_STATE						
	"DEMARRER LE JEU",							//  60 SURF_MSG_START_GAME						
	"APPUYEZ SUR UN BOUTON POUR QUITTER",		//  61 SURF_MSG_PRESS_ANY_BUTTON_TO_QUIT		
	"REJOUER NUMERO",							//  62 SURF_MSG_REPLAY_NUMBER					
	"NUMERO DE PARTIE",							//  63 SURF_MSG_GAME_NUMBER					
	"CHARGER LA PARTIE",						//  64 SURF_MSG_LOAD_GAME						
	"CHARGER LE CHAMPIONNAT",					//  65 SURF_MSG_LOAD_CHAMPIONSHIP				
	"CHARGER LA REDIFFUSION",					//  66 SURF_MSG_LOAD_REPLAY					
	"SELECTIONNEZ LA PARTIE",					//  67 SURF_MSG_SELECT_GAME
	"SELECTIONNEZ REDIFFUSER",					//  68 SURF_MSG_SELECT_REPLAY					
	"A CHARGER",								//  69 SURF_MSG_TO_LOAD						
	"OPTIONS",									//  70 SURF_MSG_OPTIONS						
	"QUITTER",									//  71 SURF_MSG_QUIT							
	"REPRENDRE",								//  72 SURF_MSG_RESUME							
	"JUGEMENT",									//  73 SURF_MSG_JUDGING						
	"REDIFFUSER INSTANTANEMENT",				//  74 SURF_MSG_INSTANT_REPLAY					
	"ENREGISTRER LA REDIFFUSION",				//  75 SURF_MSG_SAVE_REPLAY					
	"ENREGISTRER SOUS",							//  76 SURF_MSG_SAVE_AS_NEW					
	"REMPLACER",								//  77 SURF_MSG_OVERWRITE						
	"RELENTI",									//  78 SURF_MSG_SLOMO_AIR						
	"REGLER L\134ECRAN",						//  79 SURF_MSG_ADJUST_SCREEN					
	"SON",										//  80 SURF_MSG_SOUND							
	"MUSIQUE",									//  81 SURF_MSG_MUSIC							
	"SELECTIONNER",								//  82 SURF_MSG_SELECT							
	"PRECEDENT",								//  83 SURF_MSG_GO_BACK						
	"PAS DE MANETTE",							//  84 SURF_MSG_CONTROLLER_REMOVED
	"LA MANETTE",								//  85 SURF_MSG_THE_CONTROLLER			
	"PRO BODYBOARDING",							//  86 SURF_MSG_PRO_BODYBOARDING
	"QUITTEZ LA PARTIE?",						//  87 SURF_MSG_QUIT_GAME_Q
	"REINSEREZ",								//  88 SURF_MSG_PLEASE_REINSERT				
	"UNE MANETTE DANS",							//  89 SURF_MSG_A_CONTROLLER_INTO				
	"LE PORT 1",								//  90 SURF_MSG_CONTROLLER_PORT_1				
	"APPUYEZ SUR DEMARRER POUR CONTINUER",		//  91 SURF_MSG_PRESS_START_TO_CONTINUE		
	"PORT DE MANETTE N",						//  92 SURF_MSG_CONTROLLER_PORT							
	"TOUR D\134ESSAI",							//  93 SURF_MSG_FREERIDE						
	"ECRAN FRACTIONNE",							//  94 SURF_MSG_SPLIT_SCREEN					
	"HAUTEUR",									//  95 SURF_MSG_BIG_AIR						
	"CONCOURS DE PLAGE",						//  96 SURF_MSG_BEACH_CONTEST					
	"CHAMPIONNAT",								//  97 SURF_MSG_RIDER_CHAMPIONSHIP				
	"ACROBATIES",								//  98 SURF_MSG_EXTREME_TRICK					
	"SELECTIONNER UN SPORT",					//  99 SURF_MSG_SELECT_SPORT					
	"SURF",										// 100 SURF_MSG_SURFING						
	"SCOOTER DES MERS",							// 101 SURF_MSG_JET_WATERCRAFT					
	"PLANCHE A VOILE",							// 102 SURF_MSG_WINDSURFING					
	"PLANCHE",									// 103 SURF_MSG_BODYBOARD_RIDING				
	"CENTRER L\134ECRAN",						// 104 SURF_MSG_CENTRE_SCREEN					
	"COMMANDES",								// 105 SURF_MSG_CONTROLS						
	"VIBRATIONS",								// 106 SURF_MSG_VIBRATION						
	"CONCOURS DE HAUTEUR",						// 107 SURF_MSG_BIG_AIR_COMPETITION				
	"JOUEURS?",									// 108 SURF_MSG_PLAYERS_Q						
	"LIMITE DE TEMPS",							// 109 SURF_MSG_CATCH_A_WAVE					
	"POUR CHEVAUCHER UNE VAGUE?",				// 110 SURF_MSG_TIME_LIMIT_Q					
	"SESSION",									// 111 SURF_MSG_SESSION						
	"DUREE DE",									//*112 SURF_MSG_TIME_OF							
	"DUREE DE VAGUE",							// 113 SURF_MSG_WAVE_TIME						
	"SELECTIONNER UN PARTICIPANT",				// 114 SURF_MSG_SELECT_RIDER					
	"MARK",										// 115 SURF_MSG_MARK							
	"SUMMER",									// 116 SURF_MSG_SUMMER							
	"CRYSTAL",									// 117 SURF_MSG_CRYSTAL						
	"CAM",										// 118 SURF_MSG_CAM							
	"BEAR",										// 119 SURF_MSG_BEAR							
	"TANIA",									// 120 SURF_MSG_TANIA							
	"CHOOK",									// 121 SURF_MSG_CHOOK							
	"JAIMIE",									// 122 SURF_MSG_JAIMIE							
	"SELECTIONNER UNE PLAGE",					// 123 SURF_MSG_SELECT_CRAFT					
	"SELECT BEACH",								// 124 SURF_MSG_SELECT_BEACH					
	"LAGUNA BEACH",								// 125 SURF_MSG_LAGUNA_BEACH					
	"SAN DIEGO",								// 126 SURF_MSG_SAN_DIEGO						
	"TORREY PINE",								// 127 SURF_MSG_TORREY_PINE					
	"BIG SUR COAST",							// 128 SURF_MSG_BIG_SUR_COAST					
	"SANTA CRUZ",								// 129 SURF_MSG_SANTA_CRUZ						
	"SONOMA COAST",								// 130 SURF_MSG_SONOMA_COAST					
	"FORT BRAGG",								// 131 SURF_MSG_FORT_BRAGG						
	"MALIBU",									// 132 SURF_MSG_MALIBU							
	"SELECTIONNER UNE PLANCHE",					// 133 SURF_MSG_SELECT_BOARD					
	"J",										// 134 SURF_MSG_P								
	"MENU DU MODE DE TEST",						// 135 SURF_MSG_TEST_MODE_MENU					
	"JOUEUR",									// 136 SURF_MSG_PLAYER							
	"PRET?",									// 137 SURF_MSG_READY_Q						
	"APPUYEZ  ",								// 138 SURF_MSG_PRESS__						
	"ETES-VOUS SUR?",							// 139 SURF_MSG_ARE_YOU_SURE_Q					
	"ENREGISTRER L\134ETAT DE LA PARTIE?",		// 140 SURF_MSG_SAVE_GAME_STATE_Q				
	"ENREGISTRER L\134ETAT DE LA PARTIE",		// 141 SURF_MSG_SAVE_GAME_STATE				
	"OUI",										// 142 SURF_MSG_YES							
	"NON",										// 143 SURF_MSG_NO								
	"ACTIVE",									// 144 SURF_MSG_ON								
	"DESACTIVE",								// 145 SURF_MSG_OFF							
	"RESULTATS DE HAUTEUR",						// 146 SURF_MSG_BIG_AIR_RESULTS				
	"NOM",										// 147 SURF_MSG_NAME							
	"HAUTEUR",									// 148 SURF_MSG_HEIGHT							
	"LIEU",										// 149 SURF_MSG_PLACE							
	"VAINQUEUR DE HAUTEUR",						// 150 SURF_MSG_BIG_AIR_WINNER					
	"FELICITATIONS",							// 151 SURF_MSG_CONGRATULATIONS				
	"REJOUER?",									// 152 SURF_MSG_PLAY_AGAIN_Q					
	"SCORE",									// 153 SURF_MSG_SCORE							
	"RESULTATS DU CONCOURS DE PLAGE",			// 154 SURF_MSG_BEACH_CONTEST_RESULTS			
	"RESULTAT DU CHAMPIONNAT DE COMPETITION",	// 155 SURF_MSG_RIDER_CHAMPIONSHIP_RESULTS		
	"VAINQUEUR DU CHAMPIONNAT DE PLAGE",		// 156 SURF_MSG_CHAMPIONSHIP_BEACH_WINNER		
	"VAINQUEUR DU CONCOURS DE PLAGE",			// 157 SURF_MSG_BEACH_CONTEST_WINNER			
	"POINTS",									// 158 SURF_MSG_POINTS							
	"CLASSEMENT DU CHAMPIONNAT",				// 159 SURF_MSG_CHAMPIONSHIP_PLACINGS			
	"VAINQUEUR DU CHAMPIONNAT",					// 160 SURF_MSG_CHAMPIONSHIP_WINNER			
	"RESULTATS D\134ACROBATIES",				// 161 SURF_MSG_EXTREME_TRICK_RESULTS			
	"VAINQUEUR D\134ACROBATIES",				// 162 SURF_MSG_EXTREME_TRICK_WINNER			
	"SCORE DU JUGE?",							// 163 SURF_MSG_JUDGES_SCORE_Q					
	"SCORE DE VAGUE",							// 164 SURF_MSG_WAVE_SCORE						
	"PLAGE SUIVANTE",							// 165 SURF_MSG_NEXT_BEACH						
	"ENREGISTRER PARTIE",						// 166 SURF_MSG_SAVE_GAME						
	"AFFICHER CLASSEMENT",						// 167 SURF_MSG_SHOW_PLACINGS					
	"MEILLEUR",									// 168 SURF_MSG_BEST							
	"PREMIER",									// 169 SURF_MSG_HIGHEST						
	"COURANT",									// 170 SURF_MSG_CURRENT						
	"HAUTEUR",									// 171 SURF_MSG_AIR							
	"SCORE 1",									// 172 SURF_MSG_BEST_SCORE_1					
	"SCORE 2",									// 173 SURF_MSG_BEST_SCORE_2					
	"SCORE 3",									// 174 SURF_MSG_BEST_SCORE_3					
	" 0.00",									// 175 SURF_MSG_ZERO_POINT_ZERO_ZERO			
	"CONCOURS",									// 176 SURF_MSG_CONTEST						
	"CHAMPIONNAT",								// 177 SURF_MSG_CHAMPIONSHIP					
	"ACROBATIES",								// 178 SURF_MSG_EXTREME						
	"REDIFFUSER",								// 179 SURF_MSG_REPLAY							
	"DEMO",										// 180 SURF_MSG_DEMO							
	"GRAPHIQUES",								// 181 SURF_MSG_GRAPHICS						
	"DIRECTION",								// 182 SURF_MSG_CUTBACK						
	"SPIN AVANT",								// 183 SURF_MSG_FORWARD_SPIN					
	"SPIN INVERSE",								// 184 SURF_MSG_REVERSE_SPIN					
	"ROULEAU AERIEN",							// 185 SURF_MSG_AIR_ROLL						
	"EL ROLLO",									// 186 SURF_MSG_EL_ROLLO						
	"TONNEAU",									// 187 SURF_MSG_BARREL_ROLL					
	"HAUTEUR INVERSE",							// 188 SURF_MSG_INVERTED_AIR					
	"SPIN AVANT EN HAUTEUR",					// 189 SURF_MSG_AIR_FORWARD_SPIN				
	"SPIN INVERSE EN HAUTEUR",					// 190 SURF_MSG_AIR_REVERSE_SPIN				
	"SPIN ROULEAU EN HAUTEUR",					// 191 SURF_MSG_AIR_ROLL_SPIN					
	"SAUT PERILLEUX ARRIERE",					// 192 SURF_MSG_BACKFLIP						
	"SAUT PERILLEUX AVANT",						// 193 SURF_MSG_FRONTFLIP						
	"DOUBLE ROULEAU EN HAUTEUR",				// 194 SURF_MSG_DOUBLE_AIR_ROLL				
	"DOUBLE EL ROLLO",							// 195 SURF_MSG_DOUBLE_EL_ROLLO				
	"DOUBLE TONNEAU",							// 196 SURF_MSG_DOUBLE_BARREL_ROLL				
	"INVERSEMENT DOUBLE EN HAUTEUR",			// 197 SURF_MSG_DOUBLE_REVERSE_AIR				
	"AVANT DOUBLE EN HAUTEUR",					// 198 SURF_MSG_DOUBLE_FORWARD_AIR				
	"INCONNU",									// 199 SURF_MSG_UNKNOWN						
	"HAUTEUR",									// 200 SURF_MSG_JETRACER
	"RETOMBER",									// 201 SURF_MSG_REENTRY						
	"RETOMBER EN HAUTEUR",						// 202 SURF_MSG_AIR_REENTRY					
	"360 DEGRES",								// 203 SURF_MSG_THREE_SIXTY					
	"VIRAGE ABAISSE",							// 204 SURF_MSG_BOTTOM_HAND_TURN				
	"VOLUME",									// 205 SURF_MSG_VOLUME							
	"SUR LE TONNEAU!",							// 206 SURF_MSG_BARREL_RIDE					
	"360 DEGRES AVANT EN HAUTEUR",				// 207 SURF_MSG_FRONT_AIR_360					
	"360 DEGRES ARRIERE EN HAUTEUR",			// 208 SURF_MSG_BACK_AIR_360					
	"720 DEGRES AVANT EN HAUTEUR",				// 209 SURF_MSG_FRONT_AIR_720					
	"720 DEGRES ARRIERE EN HAUTEUR",			// 210 SURF_MSG_BACK_AIR_720					
	"SUPERMAN!",								// 211 SURF_MSG_SUPERMAN						
	"180 DEGRES EN HAUTEUR",					// 212 SURF_MSG_AIR_180						
	"180 DEGRES BRONCO EN HAUTEUR",				// 213 SURF_MSG_BRONCO_AIR_180					
	"WHITE HOT",								// 214 SURF_MSG_WHITE_HOT						
	"LEAP-FROG",								// 215 SURF_MSG_LEAP_FROG						
	"THE DART",									// 216 SURF_MSG_THE_DART						
	"WAVE JUMPER",								// 217 SURF_MSG_WAVE_JUMPER					
	"OCEAN BLUE",								// 218 SURF_MSG_OCEAN_BLUE						
	"WAVE RIDER",								// 219 SURF_MSG_WAVE_RIDER						
	"FREE RIDE",								// 220 SURF_MSG_FREE_RIDE						
	"BUMP N JUMP",								// 221 SURF_MSG_BUMP_N_JUMP					
	"SLASH",									// 222 SURF_MSG_SLASH							
	"YELLOW CURL",								// 223 SURF_MSG_YELLOW_CURL							
	"PACIFIC BLUE",								// 224 SURF_MSG_PACIFIC_BLUE					
	"QUICK SNAP",								// 225 SURF_MSG_QUICK_SNAP						
	"STYLE RIDER",								// 226 SURF_MSG_STYLE_RIDER					
	"REDBACK",									// 227 SURF_MSG_REDBACK						
	"SHARK TOOTH",								// 228 SURF_MSG_SHARK_TOOTH					
	"SUNSET",									// 229 SURF_MSG_SUNSET							
	"PINE LIME",								// 230 SURF_MSG_PINE_LIME						
	"SWISH",									// 231 SURF_MSG_SWISH							
	"POISON TIP",								// 232 SURF_MSG_POISON_TIP						
	"-",										// 233 SURF_MSG_UNUSED_3
	"TUBES RULE",								// 234 SURF_MSG_TUBES_RULE						
	"FLAME OUT",								// 235 SURF_MSG_FLAME_OUT						
	"RAINBOW",									// 236 SURF_MSG_RAINBOW						
	"IN ZONE",									// 237 SURF_MSG_IN_ZONE						
	"CONCEPT",									// 238 SURF_MSG_CONCEPT						
	"SWIFT",									// 239 SURF_MSG_SWIFT							
	"CANNIBAL",									// 240 SURF_MSG_CANNIBAL						
	"DART",										// 241 SURF_MSG_DART							
	"DEVIL_RAY",								// 242 SURF_MSG_DEVIL_RAY						
	"PRO X5T",									// 243 SURF_MSG_PRO_X5T						
	"MIRAGE IV",								// 244 SURF_MSG_MIRAGE_IV						
	"SABRE PRO",								// 245 SURF_MSG_SABRE_PRO						
	"WINGNUT",									// 246 SURF_MSG_WINGNUT						
	"TYPHOON",									// 247 SURF_MSG_TYPHOON						
	"CYCLONE",									// 248 SURF_MSG_CYCLONE						
	"HURRICANE",								// 249 SURF_MSG_HURRICANE							
	"CAMERA DE PLAGE",							// 250 SURF_MSG_BEACH_CAM						
	"CAMERA BATEAU",							// 251 SURF_MSG_BOAT_CAM						
	"CAMERA PHARE",								// 252 SURF_MSG_LIGHTHOUSE_CAM					
	"CAM TUYAU",								// 253 SURF_MSG_TUBE_CAM						
	"CAMERA TONNEAU",							// 254 SURF_MSG_BARREL_CAM						
	"CAMERA MOUETTE",							// 255 SURF_MSG_SEAGULL_CAM					
	"VERROUILLE",								// 256 SURF_MSG_LOCKED							
	"TOUTES LES PLAGES",						// 257 SURF_MSG_ALL_BEACHES_MUST				
	"DOIVENT ETRE",								// 258 SURF_MSG_BE_UNLOCKED					
	"DEVERROUILLEES POUR",						// 259 SURF_MSG_TO_PLAY_THIS					
	"JOUER CETTE PARTIE",						// 260 SURF_MSG_GAME							
	"VOUS AVEZ DEVERROUILLE",					// 261 SURF_MSG_YOU_HAVE_UNLOCKED				
	"LA PLAGE",									// 262 SURF_MSG_THE_BEACH						
	"MEILLEURS SCORES EN HAUTEUR",				// 263 SURF_MSG_HIGHEST_AIR					
	"SCORE D\134ACROBATIE",						// 264 SURF_MSG_EXTREME_SCORE					
	"DIFFICULTE",								// 265 SURF_MSG_DIFFICULTY						
	"COMPETENCE DU CONCURRENT",					// 266 SURF_MSG_RIDER_SKILL					
	"KOOK",										// 267 SURF_MSG_KOOK							
	"AMATEUR",									// 268 SURF_MSG_AMATEUR						
	"PRO",										// 269 SURF_MSG_PRO							
	"REMPORTER",								// 270 SURF_MSG_WIN_1_PLAYER					
	"1 JOUEUR POUR",							// 271 SURF_MSG_TO_UNLOCK						
	"DEVERROUILLER CETTE PLAGE",				// 272 SURF_MSG_THIS_BEACH						
	"760CC ASSIS",								// 273 SURF_MSG_WAVEBLASTER_WB760				
	"800CC ASSIS",								// 274 SURF_MSG_WAVEBLASTER_WB800				
	"700CC DEBOUT",								// 275 SURF_MSG_SUPERJET_700					
	"800CC ASSIS",								// 276 SURF_MSG_WAVERUNNER_GP800				
	"1200CC ASSIS",								// 277 SURF_MSG_WAVERUNNER_GP1200R
	"LANGUES: FRANCAIS",						// 278 SURF_MSG_SELECT_LANGUAGE
	"SELECTIONNER UN EQUIPEMENT",				// 279 SURF_MSG_SELECT_WATERCRAFT
	"SUR LA CARTE MEMOIRE",						// 280 SURF_MSG_ON_THE_MEMORY_CARD
	"REDIFFUSION SUR LA",						// 281 SURF_MSG_REPLAY_ON_THE
	"DE LA CARTE",								//*282 SURF_MSG_THE_MEMORY
	"SESSION?",									//*283 SURF_MSG_SESSION_Q
};

#endif // THEYER_SURFTXT_H

