#ifndef _Core_Core_h_
#define _Core_Core_h_

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include <ctype.h>
#include <stdint.h>
#include <assert.h>

#ifdef flagGCC
	#include <bits/c++config.h>
#endif

#include <Dolphin/dolphin.h>
#include <Socket/Socket.h>

#include <SimpleMedia/SimpleMedia.h>

#define __PLAT_NGC__
#define __NO_DEFS__
#define NUM_RESERVED_KEYS			100
#define _UNUSED(x)
#define BYTELIMIT(x)				(((u32)(x)) & 0xFF)
#define VID_FCC(a,b,c,d)			((BYTELIMIT(a) << 24) | (BYTELIMIT(b) << 16) | (BYTELIMIT(c) << 8) | (BYTELIMIT(d)))
#define VID_VERSION(a,b,c)			VID_FCC(a,b,c,0)
#define GP_NICK_LEN					32
#define GP_LOCATION_STRING_LEN		32
#define GP_STATUS_STRING_LEN		32

namespace Mem {class Allocator;}
namespace Ass {class CRefAsset;}
namespace Mem {class Heap; class Region;}
namespace PreFile {class FileHandle;}
namespace Game {class CGoal;}
namespace Ed {class CConcreteMetaPiece;}
namespace Script {class CScript; CScript *GetNextScript(CScript *p_script=NULL);}
struct NsAnim_PosNormPair;
struct NsAnim_BoneData;
struct NsBranch;
struct NsLeaf;

void		MemManagerHandlePushContext( Mem::Allocator* alloc );
void		MemManagerHandlePopContext( void );
void*		MemManagerHandleNew( size_t size, bool assert_on_fail = true, Mem::Allocator* pAlloc = NULL );
int			MemManagerHandleAvailable();
void*		MemManagerHandleReallocateDown( size_t newSize, void *pOld, Mem::Allocator* pAlloc = NULL );
void*		MemManagerHandleReallocateUp( size_t newSize, void *pOld, Mem::Allocator* pAlloc = NULL );
void*		MemManagerHandleReallocateShrink( size_t newSize, void *pOld, Mem::Allocator* pAlloc = NULL );
void		MemManagerHandleDelete( void* pAddr );
bool		MemManagerHandleValid( void* pAddr );
size_t		MemManagerHandleGetAllocSize( void* pAddr );
Mem::Heap* MemManagerHandleTopDownHeap();
Mem::Heap* MemManagerHandleBottomUpHeap();
Mem::Heap* MemManagerHandleFrontEndHeap();
Mem::Heap* MemManagerHandleScriptHeap();
Mem::Heap* MemManagerHandleNetworkHeap();
Mem::Heap* MemManagerHandleNetMiscHeap();
Mem::Heap* MemManagerHandleProfilerHeap();
Mem::Heap* MemManagerHandleDebugHeap();
Mem::Heap* MemManagerHandleSkaterHeap( int n );
Mem::Heap* MemManagerHandleSkaterInfoHeap( );
Mem::Heap* MemManagerHandleSkaterGeomHeap( int n );
Mem::Heap* MemManagerHandleInternetTopDownHeap();
Mem::Heap* MemManagerHandleInternetBottomUpHeap();
Mem::Heap* MemManagerHandleThemeHeap();
Mem::Heap* MemManagerHandleCutsceneTopDownHeap();
Mem::Heap* MemManagerHandleCutsceneBottomUpHeap();
Mem::Heap* MemManagerHandleAudioHeap();
Mem::Heap* MemManagerHandleGetHeap(u32 whichHeap);
void MemManagerHandleRemoveHeap(Mem::Heap* heap);
int  MemManagerHandleGetContextDirection();
void MemManagerHandleInitCutsceneHeap(int heap_size);
void MemManagerHandleDeleteCutsceneHeap();
Mem::Allocator* MemManagerHandleGetContextAllocator();
void MemManagerHandleDeleteSkaterHeaps();
void MemManagerHandleInitNetMiscHeap();
void MemManagerHandleDeleteNetMiscHeap();
void MemManagerHandleInitOtherHeaps();
void MemManagerHandlePushMemoryMarker(int marker);
void MemManagerHandlePopMemoryMarker(int marker);
void MemManagerHandleInitSkaterHeaps(unsigned int num_skater_heaps_required);
char* MemManagerHandleGetContextName();
Mem::Heap* MemManagerHandleCreateHeap(Mem::Region* region, int dir, char* p_name );

unsigned int AllocatorGetId(void* addr);

#include <Game/IO/Mem_stat.h>
#include "Signatrs.h"
#include <Game/Graphics/GeomNode.h>
#include <Game/Core/Types.h>
#include <Game/Net/NetConfigIf.h>
#include <Game/Assets/Anim.h>
#include <Game/Core/Atomic.h>
#include <Game/Assets/Clump.h>
#include <Game/Physics/Collision.h>
#include <Game/Core/DebugFont.h>
#include <Game/Assets/Dl.h>
#include <Game/Assets/DlMan.h>
#include <Game/Core/HashId.h>
#include <Game/Platform/HwPad.h>
#include <Game/Graphics/Light.h>
#include <Game/Assets/Material.h>
#include <Game/Assets/MatMan.h>
#include <Game/Assets/Model.h>
#include "Particle.h"
#include <Game/Core/Quat.h>
#include <Game/Graphics/Scene.h>
#include "Slerp.h"
#include <Game/Assets/Tex.h>
#include <Game/Assets/TexMan.h>
#include <Game/Graphics/Triangle.h>
#include <Game/Core/Crc.h>
#include <Game/Core/Support.h>
#include <Game/Core/Debug.h>
#include <Game/IO/MemView.h>
#include "Pcm.h"
#include <Game/IO/EzConfig.h>
#include <Game/IO/EzCommon.h>
#include <Game/Core/Defines.h>
#include "Rot90.h"
#include <Game/IO/LibEzConfig.h>
#include <Game/IO/File.h>
#include <Game/Graphics/Prim.h>
#include <Game/Core/Vector.h>
#include "Project.h"
#include <Game/Components/Module.h>
#include <Game/Core/Flags.h>
#include <Game/Core/Class.h>
#include <Game/Audio/AUDSimpleAudio.h>
#include <Game/Audio/AUDSimplePlayer.h>
#include <Game/Core/Initialize.h>
#include <Game/Scripting/ScriptDefs.h>
#include <Game/Scripting/SymbolType.h>
#include <Game/Scripting/Tokens.h>
#include <Game/Assets/ImageBasic.h>
#include <Game/Core/CompactPool.h>
#include <Game/IO/Dma.h>
#include <Game/Core/Matrix.h>
#include <Game/Core/Timer.h>
#include <Game/IO/MemDebug.h>
#include <Game/Assets/AssetTypes.h>
#include <Game/Core/Checks.h>
#include <Game/IO/Compress.h>
#include "Messages.h"
#include <Game/Core/Math.h>
#include <Game/Core/CString.h>
#include <Game/Core/StringUtils.h>
#include <Game/Core/Support2.h>
#include <Game/Core/String.h>
#include <Game/Graphics/NxSkinComponent.h>
#include <Game/Core/Config.h>
#include <Game/Core/PoolManager.h>
#include <Game/IO/ARam.h>
#include <Game/Core/BBox.h>
#include <Game/Core/Buffer.h>
#include <Game/Core/Frame.h>
#include <Game/Core/Profile.h>
#include <Game/Core/HashTable.h>
#include <Game/Core/Vector2.h>
#include <Game/Assets/Asset.h>
#include <Game/Graphics/Camera.h>
#include "List.h"
#include "Node.h"
#include "LookupTable.h"
#include <Game/Core/Macros.h>
#include <Game/Core/Matrix2.h>
#include <Game/Core/Quat2.h>
#include <Game/Core/Rect.h>
#include <Game/Core/Thread.h>
#include <Game/Assets/BonedAnimTypes.h>
#include "FaceMassage.h"
#include <Game/Assets/Texture.h>
#include <Game/Graphics/NxTexture.h>
#include <Game/Graphics/NxTextured3dPoly.h>
#include <Game/Core/MemPtr.h>
#include <Game/IO/AsyncTypes.h>
#include <Game/World/Region.h>
#include <Game/Core/Lock.h>
#include <Game/Core/Vector.inl>
#include <Game/Core/Head.h>
#include <Game/Core/Matrix.inl>
#include <Game/Core/Quat.inl>
#include "Singleton.h"
#include "RefAsset.h"
#include <Game/Assets/Material2.h>
#include <Game/Assets/Sprite.h>
#include <Game/ComponentsSkater/SkaterButton.h>
#include <Game/Core/ObjPtr.h>
#include <Game/Graphics/NxFlags.h>
#include "Sfx.h"
#include "RefCounted.h"
#include <Game/Graphics/NxSector.h>
#include <Game/Assets/AnimController.h>
#include "List2.h"
#include <Game/Core/Math2.h>
#include <Game/Graphics/NxTextured3dPoly2.h>
#include <Game/Graphics/NxWin2D.h>
#include <Game/Core/Alloc.h>
#include <Game/Core/System.h>
#include <Game/Physics/CollEnums.h>
#include <Game/Graphics/NxGeom.h>
#include <Game/Core/Handle.h>
#include <Game/Assets/CustomAnimKey.h>
#include <Game/Core/Geometry.h>
#include "Slerp2.h"
#include <Game/Components/Task.h>
#include <Game/Assets/Movies.h>
#include <Game/Components/Object.h>
#include <Game/Audio/SoundFx.h>
#include <Game/Assets/BaseAnimCtrl.h>
#include <Game/Core/BBox2.h>
#include <Game/Graphics/NxTexture2.h>
#include <Game/Graphics/NxLightMan.h>
#include "Pose.h"
#include "MovieDetails.h"
#include <Game/Core/Heap.h>
#include <Game/Components/ObjectHook.h>
#include <Game/ComponentsSkater/SkaterFlags.h>
#include <Game/Components/Hook.h>
#include <Game/Core/TimestampedFlag.h>
#include <Game/Core/Profiler.h>
#include "Shadow.h"
#include <Game/World/Terrain.h>
#include "Rail.h"
#include "Stack.h"
#include <Game/Physics/CollCache.h>
#include <Game/Components/Event.h>
#include <Game/Audio/Music.h>
#include <Game/Components/BaseComponent.h>
#include <Game/Components/BlendChannel.h>
#include <Game/Graphics/Camera2.h>
#include <Game/Graphics/Light2.h>
#include <Game/Graphics/NxLight.h>
#include <Game/Graphics/NxNewParticle.h>
#include "SuperSector.h"
#include "MemMan.h"
#include "MemTest.h"
#include "Pile.h"
#include <Game/Graphics/Render.h>
#include <Game/Graphics/Screenshot.h>
#include "Ref.h"
#include <Game/Core/Thread2.h>
#include "Search.h"
#include <Game/Platform/Gx.h>
#include <Game/Components/Task2.h>
#include <Game/Components/MotionComponent.h>
#include <Game/Components/ObjectHookManagerComponent.h>
#include <Game/Components/CompositeObject.h>
#include <Game/Graphics/Occlude.h>
#include <Game/Graphics/NxImposter.h>
#include <Game/Graphics/NxNewParticleMgr.h>
#include <Game/Graphics/NxScene.h>
#include <Game/Graphics/NxViewport.h>
#include <Game/Graphics/VectorFont.h>
#include "Demo.h"
#include <Game/Core/Pool.h>
#include <Game/Core/Poolable.h>
#include <Game/Modes/VictoryCond.h>
#include "Utils.h"
#include <Game/Modes/GoalManager.h>
#include <Game/IO/PRE.h>
#include <Game/Core/Chars.h>
#include <Game/Graphics/CameraUtil.h>
#include <Game/Core/DynamicTable.h>
#include <Game/Physics/CollTriData.h>
#include <Game/Components/PedLogicComponent.h>
#include <Game/Components/SuspendComponent.h>
#include <Game/Components/Module2.h>
#include <Game/Audio/Music2.h>
#include <Game/Net/NetClasses.h>
#include <Game/Components/ObjectManager.h>
#include <Game/Core/Array.h>
#include <Game/Scripting/Script.h>
#include <Game/Components/Component.h>
#include "Structure.h"
#include <Game/Scripting/SymbolTable.h>
#include <Game/Core/VectorPair.h>
#include <Game/Components/ScreenElement2.h>
#include <Game/Graphics/NxLight2.h>
#include <Game/Graphics/NxFont.h>
#include <Game/Graphics/NxSprite.h>
#include <Game/Graphics/NxViewMan.h>
#include <Game/Physics/Contact.h>
#include <Game/Physics/MovingObject.h>
#include <Game/World/EdRail.h>
#include <Game/Platform/SioDev.h>
#include <Game/Graphics/NxModel.h>
#include <Game/Physics/Collision2.h>
#include <Game/Physics/CarPhysicsComponent.h>
#include <Game/Components/EmptyComponent.h>
#include <Game/Physics/NearComponent.h>
#include <Game/Components/NodeArrayComponent.h>
#include <Game/Components/RailManagerComponent.h>
#include <Game/Components/SetDisplayMatrixComponent.h>
#include <Game/Components/SkitchComponent.h>
#include <Game/Components/StreamComponent.h>
#include <Game/Net/NetServer.h>
#include <Game/IO/File2.h>
#include <Game/IO/CasUtils.h>
#include <Game/Graphics/DebugGfx.h>
#include <Game/Graphics/FaceTexture.h>
#include <Game/Graphics/GfxMan.h>
#include <Game/Graphics/GfxUtils.h>
#include <Game/Assets/ModelAppearance.h>
#include <Game/Graphics/NxNewParticleMgr2.h>
#include <Game/Graphics/NxViewport2.h>
#include <Game/Graphics/NxLoadScreen.h>
#include <Game/Graphics/NxParticle.h>
#include <Game/Graphics/NxWeather.h>
#include <Game/Assets/Skeleton.h>
#include <Game/ComponentsSkater/SkaterStateComponent.h>
#include <Game/Components/Buddy.h>
#include <Game/Modes/GameFlow.h>
#include <Game/Modes/GoalPed.h>
#include <Game/ComponentsSkater/Skate.h>
#include <Game/World/PathMan.h>
#include <Game/World/Records.h>
#include <Game/World/Restart.h>
#include <Game/ComponentsSkater/SkaterTricks.h>
#include "ParkGen.h"
#include <Game/Modes/GsInit.h>
#include <Game/IO/AsyncFileSys.h>
#include <Game/IO/Hed.h>
#include "Pip.h"
#include <Game/Platform/SioMan.h>
#include "TrickObject.h"
#include <Game/ComponentsSkater/SkaterPad.h>
#include <Game/Modes/CreateATrick.h>
#include "GameMsg.h"
#include "Score.h"
#include <Game/Assets/AssMan.h>
#include <Game/Physics/BatchTriColl.h>
#include "MovCollMan.h"
#include <Game/Graphics/CameraComponent.h>
#include <Game/Components/LockObjComponent.h>
#include <Game/World/ProximTriggerComponent.h>
#include <Game/Components/InpMan.h>
#include <Game/Net/NetClnt.h>
#include "Prefs.h"
#include <Game/Modes/Evaluate.h>
#include "Parse.h"
#include <Game/Scripting/ScriptCache.h>
#include <Game/Graphics/BlurEffect.h>
#include <Game/UI/ScrollingMenu.h>
#include <Game/UI/Window.h>
#include <Game/Graphics/NxFont2.h>
#include <Game/Graphics/NxSprite2.h>
#include <Game/Graphics/Nx.h>
#include <Game/Graphics/NxFontMan.h>
#include <Game/ComponentsSkater/SkaterSoundComponent.h>
#include <Game/Physics/Feeler.h>
#include <Game/Physics/RectFeeler.h>
#include <Game/Modes/Goal.h>
#include <Game/Modes/Gap.h>
#include "Ped.h"
#include <Game/Modes/GapManager.h>
#include <Game/IO/GsFile.h>
#include "NodeArray.h"
#include <Game/IO/FileLibrary.h>
#include <Game/Assets/Anim2.h>
#include <Game/Graphics/NxHierarchy.h>
#include <Game/Components/ObjectTrack.h>
#include <Game/Assets/SkeletonComponent.h>
#include "ModMan.h"
#include <Game/Components/VibrationComponent.h>
#include <Game/ComponentsSkater/SkaterProfile.h>
#include <Game/Assets/AnimAsset.h>
#include <Game/Assets/CutSceneAsset.h>
#include "NodeArrayAsset.h"
#include <Game/Assets/SkeletonAsset.h>
#include "SkinAsset.h"
#include <Game/Physics/CollisionComponent.h>
#include <Game/Components/InputComponent.h>
#include <Game/Assets/ModelLightUpdateComponent.h>
#include <Game/Components/MovableContactComponent.h>
#include <Game/Components/RibbonComponent.h>
#include <Game/Components/TriggerComponent.h>
#include <Game/Components/WeaponComponent.h>
#include <Game/Core/Checksum.h>
#include <Game/Core/Debugger.h>
#include <Game/UI/Menu2.h>
#include <Game/UI/SpriteElement.h>
#include <Game/UI/TextElement.h>
#include <Game/Assets/BonedAnim.h>
#include <Game/Graphics/ModelBuilder.h>
#include <Game/Graphics/Mesh.h>
#include <Game/Graphics/NxAnimCache.h>
#include <Game/Graphics/NxParticleMgr.h>
#include <Game/Graphics/NxQuickAnim.h>
#include <Game/Graphics/NxTexMan.h>
#include <Game/Net/GameNet.h>
#include <Game/Components/GameObj.h>
#include "Manual.h"
#include "PathOb.h"
#include <Game/ComponentsSkater/Skater.h>
#include <Game/ComponentsSkater/SkaterCam.h>
#include <Game/World/EdMap.h>
#include <Game/Assets/AnimationComponent.h>
#include <Game/Components/AvoidComponent.h>
#include <Game/Physics/CollideAndDieComponent.h>
#include <Game/Components/FloatingLabelComponent.h>
#include <Game/Components/ModelComponent.h>
#include <Game/Components/ParticleComponent.h>
#include <Game/Physics/RigidBodyComponent.h>
#include <Game/Components/ShadowComponent.h>
#include <Game/Audio/SoundComponent.h>
#include <Game/Components/SpecialItemComponent.h>
#include <Game/ComponentsVehicle/VehicleComponent.h>
#include <Game/Components/VelocityComponent.h>
#include <Game/Components/ScreenElemMan.h>
#include <Game/Scripting/Import.h>
#include <Game/Graphics/Scene2.h>
#include <Game/ComponentsSkater/SkaterEndRunComponent.h>
#include <Game/ComponentsSkater/SkaterNonLocalNetLogicComponent.h>
#include <Game/ComponentsSkater/SkaterPhysicsControlComponent.h>
#include <Game/ComponentsSkater/SkaterProximityComponent.h>
#include <Game/Net/Lobby.h>
#include <Game/Scripting/Content.h>
#include <Game/Modes/BettingGuy.h>
#include <Game/Modes/CATGoal.h>
#include <Game/Modes/CompetitionGoal.h>
#include <Game/Modes/FilmGoal.h>
#include <Game/Modes/FindGapsGoal.h>
#include <Game/Modes/Horse.h>
#include <Game/Modes/HorseGoal.h>
#include <Game/Modes/Minigame.h>
#include <Game/Net/NetGoal.h>
#include <Game/Modes/RaceGoal.h>
#include <Game/ComponentsSkater/SkatetrisGoal.h>
#include <Game/UI/Viewer.h>
#include <Game/ComponentsVehicle/Car.h>
#include <Game/Modes/Crown.h>
#include <Game/Assets/CutSceneDetails.h>
#include <Game/Graphics/Emitter.h>
#include "MovieCam.h"
#include "Proxim.h"
#include <Game/ComponentsSkater/SkaterCareer.h>
#include <Game/UI/ViewerObj.h>
#include "ParkEd.h"
#include <Game/Graphics/NxMesh.h>
#include <Game/ComponentsSkater/SkaterFinalizePhysicsComponent.h>
#include <Game/ComponentsSkater/SkaterMatrixQueriesComponent.h>
#include <Game/Graphics/CameraLookAroundComponent.h>
#include <Game/ComponentsVehicle/VehicleSoundComponent.h>
#include <Game/Graphics/Element3d.h>
#include "Instance.h"
#include <Game/Graphics/NxScene2.h>
#include <Game/Graphics/NxMiscFX.h>
#include "SubAnimCtrl.h"
#include <Game/Components/EditorCameraComponent.h>
#include <Game/Modes/GoalEditorComponent.h>
#include <Game/Components/ProjectileCollisionComponent.h>
#include <Game/World/RailEditorComponent.h>
#include <Game/ComponentsSkater/SkaterAdjustPhysicsComponent.h>
#include <Game/ComponentsSkater/SkaterBalanceTrickComponent.h>
#include <Game/ComponentsSkater/SkaterCleanupStateComponent.h>
#include <Game/ComponentsSkater/SkaterFloatingNameComponent.h>
#include <Game/ComponentsSkater/SkaterLoopingSoundComponent.h>
#include <Game/ComponentsSkater/SkaterScoreComponent.h>
#include <Game/Audio/Sounds.h>
#include "Stats.h"
#include <Game/UI/FrontEnd.h>
#include <Game/Modes/Competition.h>
#include <Game/Modes/GameMode.h>
#include "PlayerProfileManager.h"
#include <Game/Scripting/CFuncs.h>
#include <Game/Scripting/FTables.h>
#include "McFuncs.h"
#include "SkFuncs.h"
#include <Game/Components/StaticVehicleComponent.h>
#include <Game/ComponentsVehicle/VehicleCameraComponent.h>
#include <Game/Components/WalkCameraComponent.h>
#include "Particles.h"
#include <Game/Graphics/NxMesh2.h>
#include <Game/Graphics/NxModel2.h>
#include <Game/Graphics/NxSector2.h>
#include <Game/ComponentsSkater/SkaterCorePhysicsComponent.h>
#include <Game/ComponentsSkater/SkaterRunTimerComponent.h>
#include <Game/UI/Clipboard.h>
#include <Game/ComponentsSkater/SkaterCameraComponent.h>
#include <Game/Components/StatsManagerComponent.h>
#include <Game/Components/TrickComponent.h>
#include <Game/Components/WalkComponent.h>
#include <Game/Graphics/Render2.h>
#include <Game/Graphics/NxGeom2.h>
#include <Game/ComponentsSkater/SkaterFlipAndRotateComponent.h>
#include <Game/ComponentsSkater/SkaterGapComponent.h>
#include <Game/ComponentsSkater/SkaterLocalNetLogicComponent.h>
#include <Game/ComponentsSkater/SkaterRotateComponent.h>
#include <Game/ComponentsSkater/SkaterStateHistoryComponent.h>
#include "Replay.h"
#include <Game/Assets/Movies2.h>
#include <Game/Components/CompositeObjectManager.h>
#include "Line.h"
#include <Game/Graphics/NxInit.h>
#include <Game/Graphics/NxImposter2.h>
#include <Game/Graphics/NxParticle2.h>
#include <Game/ComponentsSkater/SkaterStancePanelComponent.h>
#include <Game/Graphics/Display.h>
#include <Game/IO/Dvd.h>
#include <Game/Core/Assert.h>
#include "Keyboard.h"
#include <Game/Core/HeapSizes.h>
#include "PcmIOp.h"
#include "BgmI.h"
#include <Game/Platform/Hw.h>
#include "Language.h"
#include <Game/Scripting/ScriptDebugger.h>
#include "ExportMsg.h"
#include "EzMain.h"
#include <Game/IO/FileSys.h>
#include <Game/Components/FollowOb.h>
#include <Game/Core/StringHashTable.h>
#include "McMan.h"
#include <Game/Graphics/NxWin2D2.h>
#include <Game/Components/ObjectSearch.h>
#include <Game/Components/BouncyComponent.h>
#include "MainLoop.h"
#include <Game/IO/AsyncFileSys.h>
#include <Game/Graphics/Grass.h>
#include <Game/Graphics/NxNewParticle2.h>
#include <Game/Graphics/NxParticleFlat.h>
#include <Game/Graphics/NxParticleGlow.h>
#include <Game/Graphics/NxParticleGlowRibbonTrail.h>
#include <Game/Graphics/NxParticleLine.h>
#include <Game/Graphics/NxParticleRibbon.h>
#include <Game/Graphics/NxParticleRibbonTrail.h>
#include <Game/Graphics/NxParticleShaded.h>
#include <Game/Graphics/NxParticleSmooth.h>
#include <Game/Graphics/NxParticleSmoothRibbon.h>
#include <Game/Graphics/NxParticleSmoothStar.h>
#include <Game/Graphics/NxParticleStar.h>
#include <Game/Graphics/NxWeather2.h>
#include "Log.h"
#include "MemFile.h"
#include "ProductCodes.h"
#include "Template.h"
#include "StdAfx.h"
#include "Glue.h"
#include "PpcwgPipe.h"
#include "RefTypes.h"
#include <Game/Components/ObjectServer.h>

#endif
